#!/bin/bash

options="include_array_constraints=true,alias_analysis=true"

for dir in `ls`
do
	if [ ! -d ${dir} ] ; then
		continue;
	fi

	cd ${dir}
	echo "${dir}"

	for file in `ls *.c 2> /dev/null`
	do
		f=${file%.*}
		if [ ! -e ${f}.expected ] ; then
			echo "${f}.expected not found!"
			continue
		fi

		echo -e "${f}.c... \c"

		compi ${f}.c ${f}.tmp ${options} > /dev/null

		diff ${f}.expected ${f}.tmp > /dev/null

		if [ ! $? -eq 0 ] ; then
			echo "has changed!"
		else
			echo "OK"
			rm ${f}.tmp
		fi
	done
	
	cd ..
done
