/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   , float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   , float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned int  , void * ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   , float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned int  , char const   *  , ...) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   , float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned int  , int  , unsigned int  , char const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned int  , int  , unsigned int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   , float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned int  , unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned int  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned int  ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   , float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   unsigned int __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
extern int clock ;
extern int inbit ;
extern int isinbit ;
extern int isfull ;
extern int outbit ;
extern int isoutbit ;
extern int curr_block[64] ;
extern int pred_block[64] ;
extern int temp_block[64] ;
extern int picture_type ;
extern int mb_type ;
extern int b_num ;
extern int scan[64] ;
extern int intra_quant[64] ;
extern int non_intra_quant[64] ;
extern int quantizer_scale ;
extern int past_intra_address ;
extern int macroblock_address ;
extern int dct_zz[64] ;
extern int dct_dc_y_past ;
extern int dct_dc_cb_past ;
extern int dct_dc_cr_past ;
extern int idct_coeff[64] ;
extern int set_prev_values ;
extern int is_for_info ;
extern int full_pel_forward_vector ;
extern int forward_f ;
extern int complement_horizontal_forward_r ;
extern int complement_vertical_forward_r ;
extern int motion_horizontal_forward_code ;
extern int motion_vertical_forward_code ;
extern int recon_right_for_prev ;
extern int recon_down_for_prev ;
extern int is_back_info ;
extern int full_pel_backward_vector ;
extern int backward_f ;
extern int complement_horizontal_backward_r ;
extern int complement_vertical_backward_r ;
extern int motion_horizontal_backward_code ;
extern int motion_vertical_backward_code ;
extern int recon_right_back_prev ;
extern int recon_down_back_prev ;
extern int storage[64] ;
extern int previous_picture ;
extern int future_picture ;
extern int getinbuffer ;
extern int getbits ;
extern int to_receive ;
extern int look_only ;
extern int setoutbuffer ;
extern int putbits ;
extern int to_transmit ;
extern int vld_length[50] ;
extern int vld_bits[50] ;
extern int mb_inc[50] ;
extern int table2b2aq[50] ;
extern int table2b2bq[50] ;
extern int table2b2cq[50] ;
extern int table2b2af[50] ;
extern int table2b2bf[50] ;
extern int table2b2cf[50] ;
extern int table2b2ab[50] ;
extern int table2b2bb[50] ;
extern int table2b2cb[50] ;
extern int table2b2ai[50] ;
extern int table2b2bi[50] ;
extern int table2b2ci[50] ;
extern int table2b4[50] ;
extern int table2b5a[50] ;
extern int table2b5b[50] ;
extern int right_little ;
extern int right_big ;
extern int down_little ;
extern int down_big ;
extern int right_for ;
extern int down_for ;
extern int right_half_for ;
extern int down_half_for ;
extern int right_back ;
extern int down_back ;
extern int right_half_back ;
extern int down_half_back ;
extern int min ;
extern int max ;
extern int new_vector ;
extern int recon_right_for ;
extern int recon_down_for ;
extern int recon_right_back ;
extern int recon_down_back ;
extern int pred_temp_bit_vector ;
extern int b_00 ;
extern int b_01 ;
extern int b_10 ;
extern int p_i0 ;
extern int p_i1 ;
extern int p_j0 ;
extern int p_j1 ;
extern int read_done ;
extern int read_int ;
extern int vld_found ;
extern int vld_size ;
void init(void) 
{ 

  {
  return;
}
}
void inbuffer(void) 
{ register int status ;
  register int iobuffer_in ;
  register int iobuf_hd_in ;
  register int iobuf_tl_in ;
  register int iobuf_look ;
  register int i ;

  {
  status = 0;
  iobuf_hd_in = 0;
  iobuf_tl_in = 0;
  iobuf_look = 0;
  i = 0;
  while (i < 5) {
    if (isinbit == 1) {
      if ((iobuf_hd_in + 1) % 256 != iobuf_tl_in) {
        iobuffer_in = inbit;
        iobuf_hd_in = (iobuf_hd_in + 1) % 256;
      }
    }
    if ((iobuf_hd_in + 1) % 256 == iobuf_tl_in) {
      isfull = 1;
    } else {
      isfull = 0;
    }
    if (status == 0) {
      if (getbits > 0) {
        to_receive = getbits;
        iobuf_look = iobuf_tl_in;
        status = 1;
      }
    } else {
      if (status == 1) {
        while (1) {
          if (to_receive != 0) {
            if (! (iobuf_look != iobuf_hd_in)) {
              break;
            }
          } else {
            break;
          }
          getinbuffer = iobuffer_in;
          iobuf_look = (iobuf_look + 1) % 256;
          to_receive = to_receive - 1;
        }
        if (to_receive == 0) {
          status = 2;
        }
      } else {
        if (status == 2) {
          if (look_only == 0) {
            iobuf_tl_in = iobuf_look;
          }
          if (getbits == 0) {
            to_receive = -1;
            status = 0;
          }
        }
      }
    }
    i = i + 1;
  }
  return;
}
}
void read_bits(int amount ) 
{ 

  {
  if (read_done == 1) {
    read_done = 0;
    look_only = 0;
    getbits = amount;
  } else {
    if (read_done == 0) {
      if (to_receive == 0) {
        read_int = getinbuffer;
        getbits = 0;
        read_done = 1;
      }
    }
  }
  return;
}
}
void look_bits(int amount ) 
{ 

  {
  if (read_done == 1) {
    read_done = 0;
    look_only = 1;
    getbits = amount;
  } else {
    if (read_done == 0) {
      if (to_receive == 0) {
        read_int = getinbuffer;
        getbits = 0;
        read_done = 1;
      }
    }
  }
  return;
}
}
void next_vld(int start , int max_next_vld ) 
{ register int i ;
  register int vld_read ;

  {
  if (vld_found >= 0) {
    vld_found = -1;
    vld_size = start - 1;
  }
  if (vld_size == max_next_vld) {
    return;
  }
  look_bits(vld_size + 1);
  if (read_done == 1) {
    vld_size = vld_size + 1;
    i = 0;
    while (i <= vld_size - 1) {
      vld_read = getinbuffer;
      i = i + 1;
    }
    i = 0;
    while (i < 50) {
      if (vld_length[i] == vld_size) {
        if (vld_read == vld_bits[i]) {
          vld_found = i;
          i = 49;
        }
      } else {
        if (vld_length[i] > vld_size) {
          i = 49;
        }
      }
      i = i + 1;
    }
  }
  return;
}
}
void vldcontrol(void) 
{ register int i ;
  register int dct_dc_differential ;
  register int forward_f_code ;
  register int forward_r_size ;
  register int motion_horizontal_forward_r ;
  register int motion_vertical_forward_r ;
  register int backward_f_code ;
  register int backward_r_size ;
  register int motion_horizontal_backward_r ;
  register int motion_vertical_backward_r ;
  register int data_type ;
  register int data_stat ;
  register int reading_zz ;
  register int run ;
  register int level ;
  register int is_mb_quant ;
  register int is_mb_intra ;
  register int count ;
  register int vld_temp ;
  register int temp ;

  {
  data_type = 0;
  data_stat = 0;
  read_done = 1;
  vld_found = 0;
  if (data_type == 7) {
    data_type = 6;
  }
  while (data_type < 7) {
    if (clock == 1) {
      if (data_type == 0) {
        read_bits(32);
        if (read_done == 1) {
          data_stat = 0;
          switch (read_int) {
          case 435: 
          data_type = 1;
          break;
          case 440: 
          data_type = 2;
          break;
          default: ;
          if (read_int == 256) {
            data_type = 3;
          } else {
            data_type = 4;
          }
          break;
          }
        }
      } else {
        if (data_type == 1) {
          if (data_stat == 0) {
            read_bits(1);
            if (read_done == 1) {
              if (getinbuffer == 1) {
                data_stat = 1;
                count = 64;
              } else {
                data_stat = 2;
              }
            }
          } else {
            if (data_stat == 1) {
              read_bits(8);
              if (read_done == 1) {
                temp = scan[64 - count];
                intra_quant[temp] = read_int;
                count = count - 1;
                if (count == 0) {
                  data_stat = 2;
                }
              }
            } else {
              if (data_stat == 2) {
                read_bits(1);
                if (read_done == 1) {
                  if (getinbuffer == 1) {
                    data_stat = 3;
                    count = 64;
                  } else {
                    data_type = 0;
                  }
                }
              } else {
                if (data_stat == 3) {
                  read_bits(8);
                  if (read_done == 1) {
                    temp = scan[64 - count];
                    non_intra_quant[temp] = read_int;
                    count = count - 1;
                    if (count == 0) {
                      data_type = 0;
                    }
                  }
                }
              }
            }
          }
        } else {
          if (data_type == 2) {
            data_type = 0;
          } else {
            if (data_type == 3) {
              if (data_stat == 0) {
                if (picture_type < 2) {
                  temp = previous_picture;
                  previous_picture = future_picture;
                  future_picture = temp;
                }
                macroblock_address = 0;
                data_stat = 1;
              } else {
                if (data_stat == 1) {
                  read_bits(3);
                  if (read_done == 1) {
                    temp = getinbuffer;
                  }
                  switch (temp) {
                  case 1: 
                  case 2: 
                  case 3: 
                  picture_type = temp - 1;
                  break;
                  }
                  if (picture_type > 0) {
                    data_stat = 2;
                  } else {
                    data_type = 0;
                  }
                }
              }
            } else {
              if (data_stat == 2) {
                read_bits(4);
                if (read_done == 1) {
                  full_pel_forward_vector = getinbuffer;
                  forward_f_code = getinbuffer;
                  forward_r_size = forward_f_code - 1;
                  vld_temp = 1;
                  vld_temp = vld_temp * forward_r_size;
                  forward_f = vld_temp;
                  if (picture_type == 2) {
                    data_stat = 3;
                  } else {
                    data_type = 0;
                  }
                }
              } else {
                if (data_stat == 3) {
                  read_bits(4);
                  if (read_done == 1) {
                    full_pel_backward_vector = getinbuffer;
                    backward_f_code = getinbuffer;
                    backward_r_size = backward_f_code - 1;
                    vld_temp = 1;
                    vld_temp = vld_temp * backward_r_size;
                    backward_f = vld_temp;
                    data_type = 0;
                  }
                } else {
                  if (data_type == 4) {
                    read_bits(5);
                    if (read_done == 1) {
                      quantizer_scale = read_int;
                      count = 0;
                      data_type = 5;
                      data_stat = 0;
                    }
                  } else {
                    if (data_type == 5) {
                      if (data_stat == 0) {
                        look_bits(11);
                        if (read_done == 1) {
                          if (read_int == 8) {
                            data_stat = 1;
                          } else {
                            data_stat = 2;
                          }
                        }
                      } else {
                        if (data_stat == 1) {
                          read_bits(11);
                          if (read_done == 1) {
                            count = count + 1;
                            data_stat = 0;
                          }
                        } else {
                          if (data_stat == 2) {
                            next_vld(1, 11);
                            if (vld_found >= 0) {
                              data_stat = 3;
                            }
                          } else {
                            if (data_stat == 3) {
                              if (mb_inc[vld_found] == -1) {
                                vld_found = -1;
                                data_stat = 2;
                              } else {
                                if (mb_type == 0) {
                                  past_intra_address = macroblock_address;
                                }
                                read_bits(vld_size);
                                macroblock_address = (macroblock_address + 33 * count) + mb_inc[vld_found];
                                data_stat = 4;
                              }
                            } else {
                              if (data_stat == 4) {
                                next_vld(1, 6);
                                if (vld_found >= 0) {
                                  data_stat = 5;
                                }
                              } else {
                                if (data_stat == 5) {
                                  switch (picture_type) {
                                  case 0: 
                                  is_mb_quant = table2b2aq[vld_found];
                                  is_for_info = table2b2af[vld_found];
                                  is_back_info = table2b2ab[vld_found];
                                  is_mb_intra = table2b2ai[vld_found];
                                  break;
                                  case 1: 
                                  is_mb_quant = table2b2bq[vld_found];
                                  is_for_info = table2b2bf[vld_found];
                                  is_back_info = table2b2bb[vld_found];
                                  is_mb_intra = table2b2bi[vld_found];
                                  break;
                                  case 2: 
                                  is_mb_quant = table2b2cq[vld_found];
                                  is_for_info = table2b2cf[vld_found];
                                  is_back_info = table2b2cb[vld_found];
                                  is_mb_intra = table2b2bi[vld_found];
                                  break;
                                  }
                                  if (is_mb_quant == -1) {
                                    vld_found = -1;
                                    data_stat = 4;
                                  } else {
                                    if (is_for_info == -1) {
                                      vld_found = -1;
                                      data_stat = 4;
                                    } else {
                                      if (is_back_info == -1) {
                                        vld_found = -1;
                                        data_stat = 4;
                                      } else {
                                        if (is_mb_intra == -1) {
                                          vld_found = -1;
                                          data_stat = 4;
                                        } else {
                                          if (is_mb_intra == 1) {
                                            mb_type = 0;
                                          } else {
                                            mb_type = picture_type;
                                          }
                                          read_bits(vld_size);
                                          if (is_mb_quant == 1) {
                                            data_stat = 6;
                                          } else {
                                            data_stat = 7;
                                          }
                                        }
                                      }
                                    }
                                  }
                                } else {
                                  if (data_stat == 6) {
                                    read_bits(5);
                                    if (read_done == 1) {
                                      quantizer_scale = read_int;
                                      data_stat = 7;
                                    }
                                  } else {
                                    if (data_stat == 7) {
                                      if (is_for_info == 1) {
                                        data_stat = 8;
                                      } else {
                                        data_stat = 14;
                                      }
                                    } else {
                                      if (data_stat == 8) {
                                        next_vld(1, 11);
                                        if (vld_found >= 0) {
                                          data_stat = 9;
                                        }
                                      } else {
                                        if (data_stat == 9) {
                                          motion_horizontal_forward_code = table2b4[vld_found];
                                          if (motion_horizontal_forward_code == 99) {
                                            vld_found = -1;
                                            data_stat = 8;
                                          } else {
                                            read_bits(vld_size);
                                            if (forward_f == 1) {
                                              complement_horizontal_forward_r = 0;
                                              data_stat = 11;
                                            } else {
                                              if (motion_horizontal_forward_code == 0) {
                                                complement_horizontal_forward_r = 0;
                                                data_stat = 11;
                                              } else {
                                                data_stat = 10;
                                              }
                                            }
                                          }
                                        } else {
                                          if (data_stat == 10) {
                                            read_bits(forward_r_size);
                                            if (read_done == 1) {
                                              motion_horizontal_forward_r = read_int;
                                              complement_horizontal_forward_r = (forward_f - 1) - motion_horizontal_forward_r;
                                              data_stat = 11;
                                            }
                                          } else {
                                            if (data_stat == 11) {
                                              next_vld(1, 11);
                                              if (vld_found >= 0) {
                                                data_stat = 12;
                                              }
                                            } else {
                                              if (data_stat == 12) {
                                                motion_vertical_forward_code = table2b4[vld_found];
                                                if (motion_vertical_forward_code == 99) {
                                                  vld_found = -1;
                                                  data_stat = 11;
                                                } else {
                                                  read_bits(vld_size);
                                                  if (forward_f == 1) {
                                                    complement_vertical_forward_r = 0;
                                                    data_stat = 14;
                                                  } else {
                                                    if (motion_vertical_forward_code == 0) {
                                                      complement_vertical_forward_r = 0;
                                                      data_stat = 14;
                                                    } else {
                                                      data_stat = 13;
                                                    }
                                                  }
                                                }
                                              } else {
                                                if (data_stat == 13) {
                                                  read_bits(forward_r_size);
                                                  if (read_done == 1) {
                                                    motion_vertical_forward_r = read_int;
                                                    complement_vertical_forward_r = (forward_f - 1) - motion_vertical_forward_r;
                                                    data_stat = 14;
                                                  }
                                                } else {
                                                  if (data_stat == 14) {
                                                    if (is_back_info == 1) {
                                                      data_stat = 15;
                                                    } else {
                                                      b_num = 0;
                                                      data_type = 6;
                                                      data_stat = 0;
                                                    }
                                                  } else {
                                                    if (data_stat == 15) {
                                                      next_vld(1, 11);
                                                      if (vld_found >= 0) {
                                                        data_stat = 16;
                                                      }
                                                    } else {
                                                      if (data_stat == 16) {
                                                        motion_horizontal_backward_code = table2b4[vld_found];
                                                        if (motion_horizontal_backward_code == 99) {
                                                          vld_found = -1;
                                                          data_stat = 15;
                                                        } else {
                                                          read_bits(vld_size);
                                                          if (forward_f == 1) {
                                                            complement_horizontal_backward_r = 0;
                                                            data_stat = 18;
                                                          } else {
                                                            if (motion_horizontal_backward_code == 0) {
                                                              complement_horizontal_backward_r = 0;
                                                              data_stat = 18;
                                                            } else {
                                                              data_stat = 17;
                                                            }
                                                          }
                                                        }
                                                      } else {
                                                        if (data_stat == 17) {
                                                          read_bits(backward_r_size);
                                                          if (read_done == 1) {
                                                            motion_horizontal_backward_r = read_int;
                                                            complement_horizontal_backward_r = (backward_f - 1) - motion_horizontal_backward_r;
                                                            data_stat = 18;
                                                          }
                                                        } else {
                                                          if (data_stat == 18) {
                                                            next_vld(1, 11);
                                                            if (vld_found >= 0) {
                                                              data_stat = 19;
                                                            }
                                                          } else {
                                                            if (data_stat == 19) {
                                                              motion_vertical_backward_code = table2b4[vld_found];
                                                              if (motion_vertical_backward_code == 99) {
                                                                vld_found = -1;
                                                                data_stat = 18;
                                                              } else {
                                                                read_bits(vld_size);
                                                                if (forward_f == 1) {
                                                                  complement_vertical_backward_r = 0;
                                                                  b_num = 0;
                                                                  data_type = 6;
                                                                  data_stat = 0;
                                                                } else {
                                                                  if (motion_vertical_backward_code == 0) {
                                                                    complement_vertical_backward_r = 0;
                                                                    b_num = 0;
                                                                    data_type = 6;
                                                                    data_stat = 0;
                                                                  } else {
                                                                    data_stat = 20;
                                                                  }
                                                                }
                                                              }
                                                            } else {
                                                              if (data_stat == 20) {
                                                                read_bits(backward_r_size);
                                                                if (read_done == 1) {
                                                                  motion_vertical_backward_r = read_int;
                                                                  complement_vertical_backward_r = (backward_f - 1) - motion_vertical_backward_r;
                                                                  b_num = 0;
                                                                  data_type = 6;
                                                                  data_stat = 0;
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      if (data_type == 6) {
                        if (data_stat == 0) {
                          reading_zz = 1;
                          if (mb_type == 0) {
                            data_stat = 1;
                          } else {
                            data_stat = 7;
                          }
                        } else {
                          if (data_stat == 1) {
                            if (b_num < 4) {
                              data_stat = 4;
                            } else {
                              data_stat = 2;
                            }
                          } else {
                            if (data_stat == 2) {
                              next_vld(2, 8);
                              if (vld_found >= 0) {
                                data_stat = 3;
                              }
                            } else {
                              if (data_stat == 3) {
                                count = table2b5b[vld_found];
                                if (count == -1) {
                                  vld_found = -1;
                                  data_stat = 2;
                                } else {
                                  read_bits(vld_size);
                                  data_stat = 6;
                                }
                              } else {
                                if (data_stat == 4) {
                                  next_vld(2, 7);
                                  if (vld_found >= 0) {
                                    data_stat = 5;
                                  }
                                } else {
                                  if (data_stat == 5) {
                                    count = table2b5a[vld_found];
                                    if (count == -1) {
                                      vld_found = -1;
                                      data_stat = 4;
                                    } else {
                                      read_bits(vld_size);
                                      data_stat = 6;
                                    }
                                  } else {
                                    if (data_stat == 6) {
                                      if (count == 0) {
                                        dct_dc_differential = 0;
                                        dct_zz[0] = 0;
                                        data_stat = 9;
                                      } else {
                                        read_bits(count);
                                        if (read_done == 1) {
                                          if (getinbuffer == 1) {
                                            dct_zz[0] = read_int;
                                          } else {
                                            vld_temp = -1;
                                            vld_temp = vld_temp * count;
                                            vld_temp = vld_temp | (dct_dc_differential + 1);
                                            dct_zz[0] = vld_temp;
                                          }
                                          data_stat = 9;
                                        }
                                      }
                                    } else {
                                      if (data_stat == 7) {
                                        look_bits(6);
                                        if (read_done == 1) {
                                          if (read_int == 1) {
                                            read_bits(6);
                                            count = 0;
                                            data_stat = 8;
                                          } else {
                                            data_stat = 11;
                                          }
                                        }
                                      } else {
                                        if (data_stat == 8) {
                                          if (count == 0) {
                                            read_bits(6);
                                            if (read_done == 1) {
                                              run = read_int;
                                              count = 1;
                                            }
                                          }
                                          if (count == 1) {
                                            read_bits(8);
                                            if (read_done == 1) {
                                              if (read_int == 0) {
                                                count = 2;
                                              } else {
                                                if (read_int == 128) {
                                                  count = 3;
                                                } else {
                                                  if (read_int < 128) {
                                                    level = read_int;
                                                  } else {
                                                    level = read_int - 256;
                                                  }
                                                  count = 4;
                                                }
                                              }
                                            }
                                          }
                                          if (count == 2) {
                                            read_bits(8);
                                            if (read_done == 1) {
                                              level = read_int;
                                              count = 4;
                                            }
                                          }
                                          if (count == 3) {
                                            read_bits(8);
                                            if (read_done == 1) {
                                              level = read_int - 256;
                                              count = 4;
                                            }
                                          }
                                          if (count == 4) {
                                            i = 0;
                                            while (i <= run) {
                                              temp = scan[reading_zz];
                                              dct_zz[temp] = level;
                                              reading_zz = reading_zz + 1;
                                              i = i + 1;
                                            }
                                            data_stat = 9;
                                          }
                                        } else {
                                          if (data_stat == 9) {
                                            look_bits(6);
                                            if (read_done == 1) {
                                              if (read_int == 1) {
                                                read_bits(6);
                                                count = 0;
                                                data_stat = 10;
                                              } else {
                                                data_stat = 11;
                                              }
                                            }
                                          } else {
                                            if (data_stat == 10) {
                                              if (count == 0) {
                                                read_bits(6);
                                                if (read_done == 1) {
                                                  run = read_int;
                                                  count = 1;
                                                }
                                              }
                                              if (count == 1) {
                                                read_bits(8);
                                                if (read_done == 1) {
                                                  if (read_int == 0) {
                                                    count = 2;
                                                  } else {
                                                    if (read_int == 128) {
                                                      count = 3;
                                                    } else {
                                                      if (read_int < 128) {
                                                        level = read_int;
                                                      } else {
                                                        level = read_int - 256;
                                                      }
                                                      count = 4;
                                                    }
                                                  }
                                                }
                                              }
                                              if (count == 2) {
                                                read_bits(8);
                                                if (read_done == 1) {
                                                  level = read_int;
                                                  count = 4;
                                                }
                                              }
                                              if (count == 3) {
                                                read_bits(8);
                                                if (read_done == 1) {
                                                  level = read_int - 256;
                                                  count = 4;
                                                }
                                              }
                                              if (count == 4) {
                                                i = 0;
                                                while (i <= run) {
                                                  temp = scan[reading_zz];
                                                  dct_zz[temp] = level;
                                                  reading_zz = reading_zz + 1;
                                                  i = i + 1;
                                                }
                                                data_stat = 9;
                                              }
                                            } else {
                                              if (data_stat == 11) {
                                                look_bits(2);
                                                if (read_done == 1) {
                                                  if (read_int == 2) {
                                                    data_stat = 10;
                                                  } else {
                                                    data_stat = 12;
                                                  }
                                                }
                                              } else {
                                                if (data_stat == 12) {
                                                  read_bits(2);
                                                  if (read_done == 1) {
                                                    if (b_num == 5) {
                                                      data_stat = 13;
                                                    } else {
                                                      b_num = b_num + 1;
                                                      data_stat = 0;
                                                    }
                                                  }
                                                } else {
                                                  if (data_stat == 13) {
                                                    look_bits(23);
                                                    if (read_done == 1) {
                                                      if (read_int == 0) {
                                                        data_type = 0;
                                                      } else {
                                                        count = 0;
                                                        data_type = 5;
                                                        data_stat = 0;
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return;
}
}
int sign(int dec ) 
{ 

  {
  if (dec < 0) {
    return (-1);
  }
  if (dec > 0) {
    return (1);
  }
  return (0);
}
}
void dequant(void) 
{ register int i ;
  register int n ;
  register int deq_temp_bit_vector ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  if (mb_type == 0) {
    n = 0;
    while (n <= 63) {
      i = scan[n];
      curr_block[n] = (((dct_zz[i] * quantizer_scale) * intra_quant[n]) * 2) / 16;
      deq_temp_bit_vector = curr_block[n];
      if (deq_temp_bit_vector == 0) {
        tmp = sign(curr_block[n]);
        curr_block[n] = curr_block[n] - tmp;
      }
      if (curr_block[n] > 2047) {
        curr_block[n] = 2047;
      }
      if (curr_block[n] < -2047) {
        curr_block[n] = -2047;
      }
      n = n + 1;
    }
    if (b_num == 0) {
      curr_block[0] = dct_zz[0] * 8;
      if (macroblock_address - past_intra_address > 1) {
        curr_block[0] = curr_block[0] + 1024;
      } else {
        curr_block[0] = curr_block[0] + dct_dc_y_past;
      }
      dct_dc_y_past = curr_block[0];
    } else {
      if (b_num < 4) {
        curr_block[0] = dct_zz[0] * 8 + dct_dc_y_past;
        dct_dc_y_past = curr_block[0];
      } else {
        if (b_num == 4) {
          curr_block[0] = dct_zz[0] * 8;
          if (macroblock_address - past_intra_address > 1) {
            curr_block[0] = curr_block[0] + 1024;
          } else {
            curr_block[0] = curr_block[0] + dct_dc_cb_past;
          }
          dct_dc_cb_past = curr_block[0];
        } else {
          if (b_num == 5) {
            curr_block[0] = dct_zz[0] * 8;
            if (macroblock_address - past_intra_address > 1) {
              curr_block[0] = curr_block[0] + 1024;
            } else {
              curr_block[0] = curr_block[0] + dct_dc_cr_past;
            }
            dct_dc_cr_past = curr_block[0];
            past_intra_address = macroblock_address;
          }
        }
      }
    }
  } else {
    n = 0;
    while (n <= 63) {
      i = scan[n];
      tmp___0 = sign(dct_zz[i]);
      curr_block[n] = (((dct_zz[i] * 2 + tmp___0) * quantizer_scale) * non_intra_quant[n]) / 16;
      deq_temp_bit_vector = curr_block[n];
      if (deq_temp_bit_vector == 0) {
        tmp___1 = sign(curr_block[n]);
        curr_block[n] = curr_block[n] - tmp___1;
      }
      if (curr_block[n] > 2047) {
        curr_block[n] = 2047;
      }
      if (curr_block[n] < -2047) {
        curr_block[n] = -2047;
      }
      dct_zz[i] = 0;
      if (dct_zz[i]) {
        curr_block[n] = 0;
      }
      n = n + 1;
    }
  }
  return;
}
}
void idct(void) 
{ register int i ;
  register int j ;
  register int k ;

  {
  i = 0;
  while (i <= 63) {
    temp_block[i] = 0;
    i = i + 1;
  }
  i = 0;
  while (i <= 7) {
    j = 0;
    while (j <= 7) {
      k = 0;
      while (k <= 7) {
        temp_block[i * 8 + j] = temp_block[i * 8 + j] + idct_coeff[i * 8 + k] * curr_block[k * 8 + j];
        k = k + 1;
      }
      temp_block[i * 8 + j] = temp_block[i * 8 + j] / 8192;
      j = j + 1;
    }
    i = i + 1;
  }
  i = 0;
  while (i <= 63) {
    curr_block[i] = 0;
    i = i + 1;
  }
  i = 0;
  while (i <= 7) {
    j = 0;
    while (j <= 7) {
      k = 0;
      while (k <= 7) {
        curr_block[i * 8 + j] = curr_block[i * 8 + j] + temp_block[i * 8 + k] * idct_coeff[j * 8 + k];
        k = k + 1;
      }
      curr_block[i * 8 + j] = curr_block[i * 8 + j] / 8192;
      j = j + 1;
    }
    i = i + 1;
  }
  return;
}
}
void calculate_forward_motion(int new_prev_values ) 
{ 

  {
  right_little = motion_horizontal_forward_code * forward_f;
  if (right_little == 0) {
    right_big = 0;
  } else {
    if (right_little > 0) {
      right_little = right_little - complement_horizontal_forward_r;
      right_big = right_little - forward_f * 32;
    } else {
      right_little = right_little + complement_horizontal_forward_r;
      right_big = right_little + forward_f * 32;
    }
  }
  down_little = motion_vertical_forward_code * forward_f;
  if (down_little == 0) {
    down_big = 0;
  } else {
    if (down_little > 0) {
      down_little = down_little - complement_vertical_forward_r;
      down_big = down_little - forward_f * 32;
    } else {
      down_little = down_little + complement_vertical_forward_r;
      down_big = down_little + forward_f * 32;
    }
  }
  max = forward_f * 16 - 1;
  min = - (forward_f * 16);
  new_vector = recon_right_for_prev + right_little;
  if (new_vector <= max) {
    if (new_vector >= min) {
      recon_right_for = recon_right_for_prev + right_little;
    } else {
      recon_right_for = recon_right_for_prev + right_big;
    }
  } else {
    recon_right_for = recon_right_for_prev + right_big;
  }
  if (new_prev_values == 1) {
    recon_right_for_prev = recon_right_for;
  }
  if (full_pel_forward_vector == 1) {
    pred_temp_bit_vector = recon_right_for;
    pred_temp_bit_vector = pred_temp_bit_vector * 2;
    recon_right_for = pred_temp_bit_vector;
  }
  new_vector = recon_down_for_prev + down_little;
  if (new_vector <= max) {
    if (new_vector >= min) {
      recon_down_for = recon_down_for_prev + down_little;
    } else {
      recon_down_for = recon_down_for_prev + down_big;
    }
  } else {
    recon_down_for = recon_down_for_prev + down_big;
  }
  if (new_prev_values == 1) {
    recon_down_for_prev = recon_down_for;
  }
  if (full_pel_forward_vector == 1) {
    pred_temp_bit_vector = recon_down_for;
    if (pred_temp_bit_vector < 1) {
      pred_temp_bit_vector = 1;
    } else {
      pred_temp_bit_vector = 0;
    }
    recon_down_for = pred_temp_bit_vector;
  }
  if (b_num > 3) {
    recon_right_for = recon_right_for / 2;
    recon_down_for = recon_down_for / 2;
  }
  pred_temp_bit_vector = recon_right_for;
  pred_temp_bit_vector = pred_temp_bit_vector * 21;
  right_for = pred_temp_bit_vector;
  pred_temp_bit_vector = recon_down_for;
  pred_temp_bit_vector = pred_temp_bit_vector / 2;
  down_for = pred_temp_bit_vector;
  right_half_for = recon_right_for - right_for * 2;
  down_half_for = recon_down_for - down_for * 2;
  return;
}
}
void calculate_backward_motion(int new_prev_values ) 
{ 

  {
  right_little = motion_horizontal_backward_code * backward_f;
  if (right_little == 0) {
    right_big = 0;
  } else {
    if (right_little > 0) {
      right_little = right_little - complement_horizontal_backward_r;
      right_big = right_little - backward_f * 32;
    } else {
      right_little = right_little + complement_horizontal_backward_r;
      right_big = right_little + backward_f * 32;
    }
  }
  down_little = motion_vertical_backward_code * backward_f;
  if (down_little == 0) {
    down_big = 0;
  } else {
    if (down_little > 0) {
      down_little = down_little - complement_vertical_backward_r;
      down_big = down_little - backward_f * 32;
    } else {
      down_little = down_little + complement_vertical_backward_r;
      down_big = down_little + backward_f * 32;
    }
  }
  max = backward_f * 16 - 1;
  min = - (backward_f * 16);
  new_vector = recon_right_back_prev + right_little;
  if (new_vector <= max) {
    if (new_vector >= min) {
      recon_right_back = recon_right_back_prev + right_little;
    } else {
      recon_right_back = recon_right_back_prev + right_big;
    }
  } else {
    recon_right_back = recon_right_back_prev + right_big;
  }
  if (new_prev_values == 1) {
    recon_right_back_prev = recon_right_back;
  }
  if (full_pel_backward_vector == 1) {
    pred_temp_bit_vector = recon_right_back;
    pred_temp_bit_vector = pred_temp_bit_vector * 2;
    recon_right_back = pred_temp_bit_vector;
  }
  new_vector = recon_down_back_prev + down_little;
  if (new_vector <= max) {
    if (new_vector >= min) {
      recon_down_back = recon_down_back_prev + down_little;
    } else {
      recon_down_back = recon_down_back_prev + down_big;
    }
  } else {
    recon_down_back = recon_down_back_prev + down_big;
  }
  if (new_prev_values == 1) {
    recon_down_back_prev = recon_down_back;
  }
  if (full_pel_backward_vector == 1) {
    pred_temp_bit_vector = recon_down_back;
    pred_temp_bit_vector = pred_temp_bit_vector * 2;
    recon_down_back = pred_temp_bit_vector;
  }
  if (b_num > 3) {
    recon_right_back = recon_right_back / 2;
    recon_down_back = recon_down_back / 2;
  }
  pred_temp_bit_vector = recon_right_back;
  pred_temp_bit_vector = pred_temp_bit_vector / 2;
  right_back = pred_temp_bit_vector;
  pred_temp_bit_vector = recon_down_back;
  pred_temp_bit_vector = pred_temp_bit_vector / 2;
  down_back = pred_temp_bit_vector;
  if (right_back < 1) {
    right_half_back = recon_right_back - 1;
  } else {
    right_half_back = recon_right_back;
  }
  if (down_back < 1) {
    down_half_back = recon_down_back - 1;
  } else {
    down_half_back = recon_down_back;
  }
  return;
}
}
void calcid(int picture , int mb_addr , int i , int down_for_calcid , int j , int right_for_calcid ) 
{ 

  {
  b_00 = ((picture + mb_addr) + ((i + down_for_calcid) / 8) * 2) + (j + right_for_calcid) / 8;
  b_10 = ((picture + mb_addr) + (((i + down_for_calcid) + 1) / 8) * 2) + (j + right_for_calcid) / 8;
  b_01 = ((picture + mb_addr) + ((i + down_for_calcid) / 8) * 2) + ((j + right_for_calcid) + 1) / 8;
  p_i0 = (i + down_for_calcid) % 8;
  p_i1 = ((i + down_for_calcid) + 1) % 8;
  p_j0 = (j + right_for_calcid) % 8;
  p_j1 = ((j + right_for_calcid) + 1) % 8;
  return;
}
}
void pred(void) 
{ int i ;
  int j ;

  {
  i = 0;
  while (i <= 63) {
    pred_block[i] = 0;
    i = i + 1;
  }
  switch (mb_type) {
  case 0: 
  set_prev_values = 1;
  break;
  case 1: 
  i = 0;
  while (i <= 7) {
    j = 0;
    while (j <= 7) {
      calcid(previous_picture, macroblock_address, i, down_for, j, right_for);
      if (right_half_for == 0) {
        if (down_half_for == 0) {
          pred_block[i * 8 + j] = storage[(b_00 * 64 + p_i0 * 8) + p_j0];
        }
      }
      if (right_half_for == 0) {
        if (down_half_for == 1) {
          pred_block[i * 8 + j] = (storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_10 * 64 + p_i1 * 8) + p_j0]) / 2;
        }
      }
      if (right_half_for == 1) {
        if (down_half_for == 0) {
          pred_block[i * 8 + j] = (storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_01 * 64 + p_i0 * 8) + p_j1]) / 2;
        }
      }
      if (right_half_for == 1) {
        if (down_half_for == 1) {
          pred_block[i * 8 + j] = (((storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_10 * 64 + p_i1 * 8) + p_j0]) + storage[(b_00 * 64 + p_i0 * 8) + p_j0]) + storage[(b_01 * 64 + p_i0 * 8) + p_j1]) / 4;
        }
      }
      j = j + 1;
    }
    i = i + 1;
  }
  break;
  case 2: 
  if (is_for_info == 1) {
    i = 0;
    while (i <= 7) {
      j = 0;
      while (j <= 7) {
        calcid(previous_picture, macroblock_address, i, down_for, j, right_for);
        if (right_half_for == 0) {
          if (down_half_for == 0) {
            pred_block[i * 8 + j] = storage[(b_00 * 64 + p_i0 * 8) + p_j0];
          }
        }
        if (right_half_for == 0) {
          if (down_half_for == 1) {
            pred_block[i * 8 + j] = (storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_10 * 64 + p_i1 * 8) + p_j0]) / 2;
          }
        }
        if (right_half_for == 1) {
          if (down_half_for == 0) {
            if (storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_01 * 64 + p_i0 * 8) + p_j1] > 1) {
              pred_block[i * 8 + j] = 1;
            } else {
              pred_block[i * 8 + j] = 0;
            }
          }
        }
        if (right_half_for == 1) {
          if (down_half_for == 1) {
            pred_block[i * 8 + j] = (((storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_10 * 64 + p_i1 * 8) + p_j0]) + storage[(b_00 * 64 + p_i0 * 8) + p_j0]) + storage[(b_01 * 64 + p_i0 * 8) + p_j1]) / 4;
          }
        }
        j = j + 1;
      }
      i = i + 1;
    }
  } else {
    recon_right_for = recon_right_for_prev;
    recon_down_for = recon_down_for_prev;
  }
  if (is_back_info == 1) {
    i = 0;
    while (i <= 7) {
      j = 0;
      while (j <= 7) {
        calcid(future_picture, macroblock_address, i, down_for, j, right_for);
        if (right_half_for == 0) {
          if (down_half_for == 0) {
            pred_block[i * 8 + j] = pred_block[i * 8 + j] + storage[(b_00 * 64 + p_i0 * 8) + p_j0];
          }
        }
        if (right_half_for == 0) {
          if (down_half_for == 1) {
            pred_block[i * 8 + j] = pred_block[i * 8 + j] + (storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_10 * 64 + p_i1 * 8) + p_j0]) / 2;
          }
        }
        if (right_half_for == 1) {
          if (down_half_for == 0) {
            pred_block[i * 8 + j] = pred_block[i * 8 + j] + (storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_01 * 64 + p_i0 * 8) + p_j1]) / 2;
          }
        }
        if (right_half_for == 1) {
          if (down_half_for == 1) {
            pred_block[i * 8 + j] = pred_block[i * 8 + j] + (((storage[(b_00 * 64 + p_i0 * 8) + p_j0] + storage[(b_10 * 64 + p_i1 * 8) + p_j0]) + storage[(b_00 * 64 + p_i0 * 8) + p_j0]) + storage[(b_01 * 64 + p_i0 * 8) + p_j1]) / 4;
          }
        }
        j = j + 1;
      }
      i = i + 1;
    }
  } else {
    recon_right_back = recon_right_back_prev;
    recon_down_back = recon_down_back_prev;
  }
  if (is_for_info == 1) {
    if (is_back_info == 1) {
      i = 0;
      while (i <= 7) {
        j = 0;
        while (j <= 7) {
          pred_block[i * 8 + j] = pred_block[i * 8 + j] / 2;
          j = j + 1;
        }
        i = i + 1;
      }
    }
  }
  break;
  }
  return;
}
}
void plus(void) 
{ register int i ;

  {
  i = 0;
  while (i <= 63) {
    curr_block[i] = curr_block[i] + pred_block[i];
    if (curr_block[i] > 255) {
      curr_block[i] = 255;
    }
    if (curr_block[i] < 0) {
      curr_block[i] = 0;
    }
    i = i + 1;
  }
  return;
}
}
void store(void) 
{ register int i ;
  register int addr ;

  {
  if (picture_type < 2) {
    i = 0;
    while (i <= 63) {
      addr = (previous_picture + macroblock_address * 6) + b_num;
      addr = addr * 64 + i;
      storage[addr] = curr_block[i];
      i = i + 1;
    }
  }
  return;
}
}
void display(void) 
{ register int status ;
  register int addr ;
  register int i ;

  {
  i = 0;
  status = 0;
  while (status != 3) {
    if (clock == 1) {
      if (status == 0) {
        if (picture_type < 2) {
          addr = ((future_picture + macroblock_address * 6) + b_num) * 64;
          addr = addr + i;
          setoutbuffer = storage[addr];
          putbits = 8;
        } else {
          setoutbuffer = curr_block[i];
          putbits = 8;
        }
        status = 1;
      } else {
        if (status == 1) {
          if (to_transmit == 0) {
            putbits = 0;
            status = 2;
          }
        } else {
          if (status == 2) {
            i = i + 1;
            if (i > 63) {
              status = 3;
            } else {
              status = 0;
            }
          }
        }
      }
    }
  }
  return;
}
}
void outbuffer(void) 
{ register int status ;
  register int i ;

  {
  status = 0;
  i = 0;
  while (i < 5) {
    if (clock == 0) {
      if (status == 0) {
        if (putbits > 0) {
          to_transmit = putbits;
          status = 1;
        }
      } else {
        if (status == 1) {
          isoutbit = 1;
          outbit = setoutbuffer;
          to_transmit = to_transmit - 1;
          if (to_transmit == 0) {
            status = 2;
          }
        } else {
          if (status == 2) {
            isoutbit = 0;
            if (putbits == 0) {
              to_transmit = -1;
              status = 0;
            }
          }
        }
      }
    }
    i = i + 1;
  }
  return;
}
}
void execute(void) 
{ 

  {
  inbuffer();
  vldcontrol();
  dequant();
  idct();
  pred();
  plus();
  store();
  display();
  outbuffer();
  return;
}
}
int main(void) 
{ register int i ;

  {
  init();
  i = 0;
  while (i < 5) {
    execute();
    i = i + 1;
  }
  return (0);
}
}
