/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

int KernelMode  ;
int Executive  ;
int s  ;
int UNLOADED  ;
int NP  ;
int DC  ;
int SKIP1  ;
int SKIP2  ;
int MPR1  ;
int MPR3  ;
int IPC  ;
int pended  ;
int compFptr  ;
int compRegistered  ;
int lowerDriverReturn  ;
int setEventCalled  ;
int customIrp  ;
int myStatus  ;
int safety  ;
void stub_driver_init(void) 
{ 

  {
  s = NP;
  pended = 0;
  compFptr = 0;
  compRegistered = 0;
  lowerDriverReturn = 0;
  setEventCalled = 0;
  customIrp = 0;
  return;
}
}
void _BLAST_init(void) 
{ 

  {
  UNLOADED = 0;
  NP = 1;
  DC = 2;
  SKIP1 = 3;
  SKIP2 = 4;
  MPR1 = 5;
  MPR3 = 6;
  IPC = 7;
  s = UNLOADED;
  pended = 0;
  compFptr = 0;
  compRegistered = 0;
  lowerDriverReturn = 0;
  setEventCalled = 0;
  customIrp = 0;
  return;
}
}
void IofCompleteRequest(int IofCompleteRequest_Irp , int IofCompleteRequest_PriorityBoost ) ;
extern void _TRACER_abort(int i ) ;
int IofCallDriver(int IofCallDriver_DeviceObject , int IofCallDriver_Irp ) ;
int KeWaitForSingleObject(int KeWaitForSingleObject_Object , int KeWaitForSingleObject_WaitReason , int KeWaitForSingleObject_WaitMode , int KeWaitForSingleObject_Alertable , int KeWaitForSingleObject_Timeout ) ;
int KbFilter_PnP(int KbFilter_PnP_DeviceObject , int KbFilter_PnP_Irp ) 
{ int KbFilter_PnP_devExt ;
  int KbFilter_PnP_irpStack ;
  int KbFilter_PnP_status ;
  int KbFilter_PnP_event ;
  int KbFilter_PnP_DeviceObject__DeviceExtension ;
  int KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation ;
  int KbFilter_PnP_irpStack__MinorFunction ;
  int KbFilter_PnP_devExt__TopOfStack ;
  int KbFilter_PnP_devExt__Started ;
  int KbFilter_PnP_devExt__Removed ;
  int KbFilter_PnP_devExt__SurpriseRemoved ;
  int KbFilter_PnP_Irp__IoStatus__Status ;
  int KbFilter_PnP_Irp__IoStatus__Information ;
  int KbFilter_PnP_Irp__CurrentLocation ;
  int KbFilter_PnP_irpSp ;
  int KbFilter_PnP_nextIrpSp ;
  int KbFilter_PnP_nextIrpSp__Control ;
  int KbFilter_PnP_irpSp___0 ;
  int KbFilter_PnP_irpSp__Control ;
  int KbFilter_PnP_CIL___Tmp23 ;

  {
  KbFilter_PnP_status = 0;
  KbFilter_PnP_devExt = KbFilter_PnP_DeviceObject__DeviceExtension;
  KbFilter_PnP_irpStack = KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation;
  if ((KbFilter_PnP_irpStack__MinorFunction >= 0) && (KbFilter_PnP_irpStack__MinorFunction <= 0)) {
    KbFilter_PnP_irpSp = KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation;
    KbFilter_PnP_nextIrpSp = KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation - 1;
    KbFilter_PnP_nextIrpSp__Control = 0;
    safety = safety + (s - NP);
    safety = safety + (compRegistered - 0);
    compRegistered = 1;
    KbFilter_PnP_irpSp___0 = KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation - 1;
    KbFilter_PnP_irpSp__Control = 224;
    KbFilter_PnP_status = IofCallDriver(KbFilter_PnP_devExt__TopOfStack, KbFilter_PnP_Irp);
    KbFilter_PnP_CIL___Tmp23 = KbFilter_PnP_status;
    if (((long )KbFilter_PnP_CIL___Tmp23 >= 259L) && ((long )KbFilter_PnP_CIL___Tmp23 <= 259L)) {
      KeWaitForSingleObject(KbFilter_PnP_event, Executive, KernelMode, 0, 0);
    }
    if (KbFilter_PnP_status >= 0) {
      if (myStatus >= 0) {
        KbFilter_PnP_devExt__Started = 1;
        KbFilter_PnP_devExt__Removed = 0;
        KbFilter_PnP_devExt__SurpriseRemoved = 0;
      }
    }
    KbFilter_PnP_Irp__IoStatus__Status = KbFilter_PnP_status;
    myStatus = KbFilter_PnP_status;
    KbFilter_PnP_Irp__IoStatus__Information = 0;
    IofCompleteRequest(KbFilter_PnP_Irp, 0);
  } else {
    if ((KbFilter_PnP_irpStack__MinorFunction >= 23) && (KbFilter_PnP_irpStack__MinorFunction <= 23)) {
      KbFilter_PnP_devExt__SurpriseRemoved = 1;
      safety = safety + (s - NP);
      s = SKIP1;
      KbFilter_PnP_Irp__CurrentLocation = KbFilter_PnP_Irp__CurrentLocation + 1;
      KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation = KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation + 1;
      KbFilter_PnP_status = IofCallDriver(KbFilter_PnP_devExt__TopOfStack, KbFilter_PnP_Irp);
    } else {
      if ((KbFilter_PnP_irpStack__MinorFunction >= 2) && (KbFilter_PnP_irpStack__MinorFunction <= 2)) {
        KbFilter_PnP_devExt__Removed = 1;
        safety = safety + (s - NP);
        s = SKIP1;
        KbFilter_PnP_Irp__CurrentLocation = KbFilter_PnP_Irp__CurrentLocation + 1;
        KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation = KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation + 1;
        IofCallDriver(KbFilter_PnP_devExt__TopOfStack, KbFilter_PnP_Irp);
        KbFilter_PnP_status = 0;
      } else {
        safety = safety + (s - NP);
        s = SKIP1;
        KbFilter_PnP_Irp__CurrentLocation = KbFilter_PnP_Irp__CurrentLocation + 1;
        KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation = KbFilter_PnP_Irp__Tail__Overlay__CurrentStackLocation + 1;
        KbFilter_PnP_status = IofCallDriver(KbFilter_PnP_devExt__TopOfStack, KbFilter_PnP_Irp);
      }
    }
  }
  return (KbFilter_PnP_status);
}
}
extern int __VERIFIER_nondet_int() ;
void main(void) 
{ int main_status ;
  int main_irp ;
  int main_pirp ;
  int main_pirp__IoStatus__Status ;
  int main_irp_choice ;
  int main_devobj ;
  int main_CIL___Tmp8 ;
  int main_tmp_ndt_1 ;
  int TRACER_returning ;

  {
  TRACER_returning = 0;
  safety = 0;
  KernelMode = 0;
  Executive = 0;
  s = 0;
  UNLOADED = 0;
  NP = 0;
  DC = 0;
  SKIP1 = 0;
  SKIP2 = 0;
  MPR1 = 0;
  MPR3 = 0;
  IPC = 0;
  pended = 0;
  compFptr = 0;
  compRegistered = 0;
  lowerDriverReturn = 0;
  setEventCalled = 0;
  customIrp = 0;
  myStatus = 0;
  main_status = 0;
  main_pirp = main_irp;
  _BLAST_init();
  if (main_status >= 0) {
    s = NP;
    customIrp = 0;
    setEventCalled = customIrp;
    lowerDriverReturn = setEventCalled;
    compRegistered = lowerDriverReturn;
    pended = compRegistered;
    main_pirp__IoStatus__Status = 0;
    myStatus = 0;
    if ((main_irp_choice >= 0) && (main_irp_choice <= 0)) {
      main_pirp__IoStatus__Status = -1073741637;
      myStatus = -1073741637;
    }
    stub_driver_init();
    if (main_status >= 0) {
      main_CIL___Tmp8 = 1;
    } else {
      main_CIL___Tmp8 = 0;
    }
    if ((main_CIL___Tmp8 >= 0) && (main_CIL___Tmp8 <= 0)) {
      TRACER_returning = 1;
    } else {
      main_tmp_ndt_1 = __VERIFIER_nondet_int();
      if ((main_tmp_ndt_1 >= 3) && (main_tmp_ndt_1 <= 3)) {
        main_status = KbFilter_PnP(main_devobj, main_pirp);
      } else {
        TRACER_returning = 1;
      }
    }
  }
  if (TRACER_returning <= 0) {
    if ((pended >= 1) && (pended <= 1)) {
      if ((s >= NP) && (s <= NP)) {
        s = NP;
      } else {
        if ((pended >= 1) && (pended <= 1)) {
          if ((s >= MPR3) && (s <= MPR3)) {
            s = MPR3;
          } else {
            if ((s > UNLOADED) || (s < UNLOADED)) {
              if ((main_status > -1) || (main_status < -1)) {
                if ((s > SKIP2) || (s < SKIP2)) {
                  if ((s > IPC) || (s < IPC)) {
                    if ((s >= DC) && (s <= DC)) {
                      if ((pended >= 1) && (pended <= 1)) {
                        safety = safety + (main_status - 259);
                      } else {
                        if ((s >= DC) && (s <= DC)) {
                          if ((main_status >= 259) && (main_status <= 259)) {

                          }
                        } else {
                          if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                          }
                        }
                      }
                    }
                  } else {
                    if ((pended >= 1) && (pended <= 1)) {
                      safety = safety + (main_status - 259);
                    } else {
                      if ((s >= DC) && (s <= DC)) {
                        if ((main_status >= 259) && (main_status <= 259)) {

                        }
                      } else {
                        if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                        }
                      }
                    }
                  }
                } else {
                  if ((pended >= 1) && (pended <= 1)) {
                    safety = safety + (main_status - 259);
                  } else {
                    if ((s >= DC) && (s <= DC)) {
                      if ((main_status >= 259) && (main_status <= 259)) {

                      }
                    } else {
                      if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                      }
                    }
                  }
                }
              }
            }
          }
        } else {
          if ((s > UNLOADED) || (s < UNLOADED)) {
            if ((main_status > -1) || (main_status < -1)) {
              if ((s > SKIP2) || (s < SKIP2)) {
                if ((s > IPC) || (s < IPC)) {
                  if ((s >= DC) && (s <= DC)) {
                    if ((pended >= 1) && (pended <= 1)) {
                      safety = safety + (main_status - 259);
                    } else {
                      if ((s >= DC) && (s <= DC)) {
                        if ((main_status >= 259) && (main_status <= 259)) {

                        }
                      } else {
                        if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                        }
                      }
                    }
                  }
                } else {
                  if ((pended >= 1) && (pended <= 1)) {
                    safety = safety + (main_status - 259);
                  } else {
                    if ((s >= DC) && (s <= DC)) {
                      if ((main_status >= 259) && (main_status <= 259)) {

                      }
                    } else {
                      if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                      }
                    }
                  }
                }
              } else {
                if ((pended >= 1) && (pended <= 1)) {
                  safety = safety + (main_status - 259);
                } else {
                  if ((s >= DC) && (s <= DC)) {
                    if ((main_status >= 259) && (main_status <= 259)) {

                    }
                  } else {
                    if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      if ((pended >= 1) && (pended <= 1)) {
        if ((s >= MPR3) && (s <= MPR3)) {
          s = MPR3;
        } else {
          if ((s > UNLOADED) || (s < UNLOADED)) {
            if ((main_status > -1) || (main_status < -1)) {
              if ((s > SKIP2) || (s < SKIP2)) {
                if ((s > IPC) || (s < IPC)) {
                  if ((s >= DC) && (s <= DC)) {
                    if ((pended >= 1) && (pended <= 1)) {
                      safety = safety + (main_status - 259);
                    } else {
                      if ((s >= DC) && (s <= DC)) {
                        if ((main_status >= 259) && (main_status <= 259)) {

                        }
                      } else {
                        if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                        }
                      }
                    }
                  }
                } else {
                  if ((pended >= 1) && (pended <= 1)) {
                    safety = safety + (main_status - 259);
                  } else {
                    if ((s >= DC) && (s <= DC)) {
                      if ((main_status >= 259) && (main_status <= 259)) {

                      }
                    } else {
                      if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                      }
                    }
                  }
                }
              } else {
                if ((pended >= 1) && (pended <= 1)) {
                  safety = safety + (main_status - 259);
                } else {
                  if ((s >= DC) && (s <= DC)) {
                    if ((main_status >= 259) && (main_status <= 259)) {

                    }
                  } else {
                    if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                    }
                  }
                }
              }
            }
          }
        }
      } else {
        if ((s > UNLOADED) || (s < UNLOADED)) {
          if ((main_status > -1) || (main_status < -1)) {
            if ((s > SKIP2) || (s < SKIP2)) {
              if ((s > IPC) || (s < IPC)) {
                if ((s >= DC) && (s <= DC)) {
                  if ((pended >= 1) && (pended <= 1)) {
                    safety = safety + (main_status - 259);
                  } else {
                    if ((s >= DC) && (s <= DC)) {
                      if ((main_status >= 259) && (main_status <= 259)) {

                      }
                    } else {
                      if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                      }
                    }
                  }
                }
              } else {
                if ((pended >= 1) && (pended <= 1)) {
                  safety = safety + (main_status - 259);
                } else {
                  if ((s >= DC) && (s <= DC)) {
                    if ((main_status >= 259) && (main_status <= 259)) {

                    }
                  } else {
                    if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                    }
                  }
                }
              }
            } else {
              if ((pended >= 1) && (pended <= 1)) {
                safety = safety + (main_status - 259);
              } else {
                if ((s >= DC) && (s <= DC)) {
                  if ((main_status >= 259) && (main_status <= 259)) {

                  }
                } else {
                  if ((main_status > lowerDriverReturn) || (main_status < lowerDriverReturn)) {

                  }
                }
              }
            }
          }
        }
      }
    }
  }
  if (safety != 0) goto ERROR; return; ERROR:;
  return;
}
}
void stubMoreProcessingRequired(void) 
{ 

  {
  safety = safety + (s - NP);
  s = MPR1;
  return;
}
}
int KbFilter_Complete(int KbFilter_Complete_DeviceObject , int KbFilter_Complete_Irp , int KbFilter_Complete_Context ) ;
int IofCallDriver(int IofCallDriver_DeviceObject , int IofCallDriver_Irp ) 
{ int IofCallDriver_returnVal2 ;
  int IofCallDriver_compRetStatus ;
  int IofCallDriver_lcontext ;
  int IofCallDriver_tmp_ndt_2 ;
  int IofCallDriver_tmp_ndt_3 ;

  {
  if ((compRegistered > 0) || (compRegistered < 0)) {
    IofCallDriver_compRetStatus = KbFilter_Complete(IofCallDriver_DeviceObject, IofCallDriver_Irp, IofCallDriver_lcontext);
    stubMoreProcessingRequired();
  }
  IofCallDriver_tmp_ndt_2 = __VERIFIER_nondet_int();
  if ((IofCallDriver_tmp_ndt_2 >= 0) && (IofCallDriver_tmp_ndt_2 <= 0)) {
    IofCallDriver_returnVal2 = 0;
  } else {
    IofCallDriver_tmp_ndt_3 = __VERIFIER_nondet_int();
    if ((IofCallDriver_tmp_ndt_3 >= 1) && (IofCallDriver_tmp_ndt_3 <= 1)) {
      IofCallDriver_returnVal2 = -1073741823;
    } else {
      IofCallDriver_returnVal2 = 259;
    }
  }
  if ((s >= NP) && (s <= NP)) {
    s = IPC;
    lowerDriverReturn = IofCallDriver_returnVal2;
  } else {
    if ((s >= MPR1) && (s <= MPR1)) {
      if ((IofCallDriver_returnVal2 >= 259) && (IofCallDriver_returnVal2 <= 259)) {
        s = MPR3;
        lowerDriverReturn = IofCallDriver_returnVal2;
      } else {
        s = NP;
        lowerDriverReturn = IofCallDriver_returnVal2;
      }
    } else {
      safety = safety + (s - SKIP1);
      s = SKIP2;
      lowerDriverReturn = IofCallDriver_returnVal2;
    }
  }
  return (IofCallDriver_returnVal2);
}
}
void IofCompleteRequest(int IofCompleteRequest_Irp , int IofCompleteRequest_PriorityBoost ) 
{ 

  {
  safety = safety + (s - NP);
  s = DC;
  return;
}
}
int KeSetEvent(int KeSetEvent_Event , int KeSetEvent_Increment , int KeSetEvent_Wait ) 
{ int KeSetEvent_l ;

  {
  setEventCalled = 1;
  return (KeSetEvent_l);
}
}
int KeWaitForSingleObject(int KeWaitForSingleObject_Object , int KeWaitForSingleObject_WaitReason , int KeWaitForSingleObject_WaitMode , int KeWaitForSingleObject_Alertable , int KeWaitForSingleObject_Timeout ) 
{ int KeWaitForSingleObject_tmp_ndt_4 ;
  int retres ;

  {
  if ((s >= MPR3) && (s <= MPR3)) {
    if ((setEventCalled >= 1) && (setEventCalled <= 1)) {
      s = NP;
      setEventCalled = 0;
    } else {
      if ((customIrp >= 1) && (customIrp <= 1)) {
        s = NP;
        customIrp = 0;
      }
    }
  } else {
    if ((customIrp >= 1) && (customIrp <= 1)) {
      s = NP;
      customIrp = 0;
    }
  }
  KeWaitForSingleObject_tmp_ndt_4 = __VERIFIER_nondet_int();
  if ((KeWaitForSingleObject_tmp_ndt_4 >= 0) && (KeWaitForSingleObject_tmp_ndt_4 <= 0)) {
    retres = 0;
  } else {
    retres = -1073741823;
  }
  return (retres);
}
}
int KbFilter_Complete(int KbFilter_Complete_DeviceObject , int KbFilter_Complete_Irp , int KbFilter_Complete_Context ) 
{ int KbFilter_Complete_event ;

  {
  KbFilter_Complete_event = KbFilter_Complete_Context;
  KeSetEvent(KbFilter_Complete_event, 0, 0);
  return (-1073741802);
}
}
