/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

int s  ;
int NP  ;
int SKIP1  ;
int compRegistered  ;
int safety  ;
extern int __VERIFIER_nondet_int() ;
extern int _SLICE() ;
void main(void) 
{ int main_tmp_ndt_1 ;
  int KbFilter_PnP_irpStack__MinorFunction ;
  int IofCallDriver_tmp_ndt_2 ;
  int IofCallDriver_tmp_ndt_3 ;
  int IofCallDriver_tmp_ndt_2___0 ;
  int IofCallDriver_tmp_ndt_3___0 ;
  int IofCallDriver_tmp_ndt_2___1 ;
  int IofCallDriver_tmp_ndt_3___1 ;
  int IofCallDriver_tmp_ndt_2___2 ;
  int IofCallDriver_tmp_ndt_3___2 ;

  {
  safety = 0;
  NP = 1;
  SKIP1 = 3;
  s = NP;
  compRegistered = 0;
  main_tmp_ndt_1 = __VERIFIER_nondet_int();
  if (main_tmp_ndt_1 == 3) {
    if (KbFilter_PnP_irpStack__MinorFunction == 0) {
      safety = safety + (s - NP);
      safety = safety + (compRegistered - 0);
      safety = safety + (s - NP);
      IofCallDriver_tmp_ndt_2 = __VERIFIER_nondet_int();
      if (IofCallDriver_tmp_ndt_2 == 0) {
        s = NP;
        L1: ;
        L2: 
        safety = safety + (s - NP);
        L3: ;
        L4: 
        if (safety != 0) goto ERROR; return; ERROR:;
      } else {
        if (IofCallDriver_tmp_ndt_2 < 0) {
          L5: 
          IofCallDriver_tmp_ndt_3 = __VERIFIER_nondet_int();
          if (IofCallDriver_tmp_ndt_3 == 1) {
            s = NP;
            goto L2;
          } else {
            if (IofCallDriver_tmp_ndt_3 < 1) {
              L6: 
              s = NP;
              goto L1;
            } else {
              goto L6;
            }
          }
        } else {
          goto L5;
        }
      }
    } else {
      if (KbFilter_PnP_irpStack__MinorFunction < 0) {
        L8: 
        safety = safety + (s - NP);
        s = SKIP1;
        IofCallDriver_tmp_ndt_2___0 = __VERIFIER_nondet_int();
        if (IofCallDriver_tmp_ndt_2___0 == 0) {
          L9: 
          safety = safety + (s - SKIP1);
          goto L3;
        } else {
          if (IofCallDriver_tmp_ndt_2___0 < 0) {
            L10: 
            IofCallDriver_tmp_ndt_3___0 = __VERIFIER_nondet_int();
            if (IofCallDriver_tmp_ndt_3___0 == 1) {
              goto L9;
            } else {
              if (IofCallDriver_tmp_ndt_3___0 < 1) {
                L11: ;
                goto L9;
              } else {
                goto L11;
              }
            }
          } else {
            goto L10;
          }
        }
      } else {
        if (KbFilter_PnP_irpStack__MinorFunction == 23) {
          safety = safety + (s - NP);
          s = SKIP1;
          IofCallDriver_tmp_ndt_2___1 = __VERIFIER_nondet_int();
          if (IofCallDriver_tmp_ndt_2___1 == 0) {
            L12: 
            safety = safety + (s - SKIP1);
            goto L3;
          } else {
            if (IofCallDriver_tmp_ndt_2___1 < 0) {
              L13: 
              IofCallDriver_tmp_ndt_3___1 = __VERIFIER_nondet_int();
              if (IofCallDriver_tmp_ndt_3___1 == 1) {
                goto L12;
              } else {
                if (IofCallDriver_tmp_ndt_3___1 < 1) {
                  L14: ;
                  goto L12;
                } else {
                  goto L14;
                }
              }
            } else {
              goto L13;
            }
          }
        } else {
          if (KbFilter_PnP_irpStack__MinorFunction < 23) {
            L15: ;
            if (KbFilter_PnP_irpStack__MinorFunction == 2) {
              safety = safety + (s - NP);
              s = SKIP1;
              IofCallDriver_tmp_ndt_2___2 = __VERIFIER_nondet_int();
              if (IofCallDriver_tmp_ndt_2___2 == 0) {
                L16: 
                safety = safety + (s - SKIP1);
                goto L3;
              } else {
                if (IofCallDriver_tmp_ndt_2___2 < 0) {
                  L17: 
                  IofCallDriver_tmp_ndt_3___2 = __VERIFIER_nondet_int();
                  if (IofCallDriver_tmp_ndt_3___2 == 1) {
                    goto L16;
                  } else {
                    if (IofCallDriver_tmp_ndt_3___2 < 1) {
                      L18: ;
                      goto L16;
                    } else {
                      goto L18;
                    }
                  }
                } else {
                  goto L17;
                }
              }
            } else {
              if (KbFilter_PnP_irpStack__MinorFunction < 2) {
                goto L8;
              } else {
                goto L8;
              }
            }
          } else {
            goto L15;
          }
        }
      }
    }
  } else {
    if (main_tmp_ndt_1 < 3) {
      goto L4;
    } else {
      goto L4;
    }
  }
  return;
}
}
