/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

unsigned int Cur_Vertical_Sep  ;
unsigned int High_Confidence  ;
unsigned int Two_of_Three_Reports_Valid  ;
unsigned int Own_Tracked_Alt  ;
unsigned int Own_Tracked_Alt_Rate  ;
unsigned int Other_Tracked_Alt  ;
unsigned int Alt_Layer_Value  ;
unsigned int Positive_RA_Alt_Thresh__0  ;
unsigned int Positive_RA_Alt_Thresh__1  ;
unsigned int Positive_RA_Alt_Thresh__2  ;
unsigned int Positive_RA_Alt_Thresh__3  ;
unsigned int Up_Separation  ;
unsigned int Down_Separation  ;
unsigned int Other_RAC  ;
unsigned int Other_Capability  ;
unsigned int Climb_Inhibit  ;
extern int (_SLICE)() ;
void main(void) 
{ unsigned int enabled ;
  unsigned int tcas_equipped ;
  unsigned int intent_not_known ;
  unsigned int need_upward_RA ;
  unsigned int need_downward_RA ;
  unsigned int alt_sep ;
  unsigned int alim ;
  unsigned int temp1 ;
  unsigned int temp2 ;
  unsigned int temp3 ;
  unsigned int temp4 ;
  unsigned int result_Non_Crossing_Biased_Climb ;
  unsigned int result_Non_Crossing_Biased_Descend ;
  unsigned int upward_preferred_1 ;
  unsigned int alim_Non_Crossing_Biased_Climb ;
  unsigned int temp11 ;
  unsigned int temp12 ;
  unsigned int temp13 ;
  unsigned int upward_preferred_2 ;
  unsigned int alim_Non_Crossing_Biased_Descend ;
  unsigned int temp21 ;
  unsigned int temp22 ;
  unsigned int temp23 ;
  int myCIL___tmp ;

  int xxx;

  {
      xxx = 0;
  Positive_RA_Alt_Thresh__0 = 400U;
  Positive_RA_Alt_Thresh__1 = 500U;
  Positive_RA_Alt_Thresh__2 = 640U;
  Positive_RA_Alt_Thresh__3 = 740U;
  enabled = 0U;
  tcas_equipped = 0U;
  intent_not_known = 0U;
  need_upward_RA = 0U;
  need_downward_RA = 0U;
  if (Alt_Layer_Value == 0U) {
    alim = Positive_RA_Alt_Thresh__0;
  }
  if (Alt_Layer_Value == 1U) {
    alim = Positive_RA_Alt_Thresh__1;
  }
  if (Alt_Layer_Value == 2U) {
    alim = Positive_RA_Alt_Thresh__2;
  }
  alim = Positive_RA_Alt_Thresh__3;
  if (High_Confidence != 0U) {
    if (Own_Tracked_Alt_Rate <= 600U) {
      if (Cur_Vertical_Sep > 600U) {
        enabled = 1U;
      }
    }
  }
  if (Other_Capability == 0U) {
    tcas_equipped = 1U;
  }
  if (Two_of_Three_Reports_Valid != 0U) {
    if (Other_RAC == 0U) {
      intent_not_known = 1U;
    }
  }
  alt_sep = 0U;
  if (enabled != 0U) {
    if (tcas_equipped != 0U) {
      if (intent_not_known != 0U) {
        goto _L___0;
      } else {
        goto _L___1;
      }
    } else {
      _L___1: /* CIL Label */ 
      if (! (tcas_equipped != 0U)) {
        _L___0: /* CIL Label */ 
        upward_preferred_1 = 0U;
        result_Non_Crossing_Biased_Climb = 0U;
        if (Alt_Layer_Value == 0U) {
          alim_Non_Crossing_Biased_Climb = Positive_RA_Alt_Thresh__0;
        }
        if (Alt_Layer_Value == 1U) {
          alim_Non_Crossing_Biased_Climb = Positive_RA_Alt_Thresh__1;
        }
        if (Alt_Layer_Value == 2U) {
          alim_Non_Crossing_Biased_Climb = Positive_RA_Alt_Thresh__2;
        }
        alim_Non_Crossing_Biased_Climb = Positive_RA_Alt_Thresh__3;
        if (Climb_Inhibit == 1U) {
          temp11 = Up_Separation + 100U;
        } else {
          temp11 = Up_Separation;
        }
        if (temp11 > Down_Separation) {
          upward_preferred_1 = 1U;
        }
        if (upward_preferred_1 == 1U) {
          if (Own_Tracked_Alt < Other_Tracked_Alt) {
            temp12 = 1U;
          } else {
            temp12 = 0U;
          }
          if (! (temp12 != 0U)) {
            result_Non_Crossing_Biased_Climb = 1U;
          } else {
            if (temp12 != 0U) {
              if (! (Down_Separation >= alim_Non_Crossing_Biased_Climb)) {
                result_Non_Crossing_Biased_Climb = 1U;
              }
            }
          }
        } else {
          if (Other_Tracked_Alt < Own_Tracked_Alt) {
            temp13 = 1U;
          } else {
            temp13 = 0U;
          }
          if (temp13 != 0U) {
            if (Cur_Vertical_Sep >= 300U) {
              if (Up_Separation >= alim_Non_Crossing_Biased_Climb) {
                result_Non_Crossing_Biased_Climb = 1U;
              }
            }
          }
        }
        temp1 = result_Non_Crossing_Biased_Climb;
        if (Own_Tracked_Alt < Other_Tracked_Alt) {
          temp2 = 1U;
        } else {
          temp2 = 0U;
        }
        if (temp1 != 0U) {
          if (temp2 != 0U) {
            need_upward_RA = 1U;
          }
        }
        upward_preferred_2 = 0U;
        result_Non_Crossing_Biased_Descend = 0U;
        if (Alt_Layer_Value == 0U) {
          alim_Non_Crossing_Biased_Descend = Positive_RA_Alt_Thresh__0;
        }
        if (Alt_Layer_Value == 1U) {
          alim_Non_Crossing_Biased_Descend = Positive_RA_Alt_Thresh__1;
        }
        if (Alt_Layer_Value == 2U) {
          alim_Non_Crossing_Biased_Descend = Positive_RA_Alt_Thresh__2;
        }
        alim_Non_Crossing_Biased_Descend = Positive_RA_Alt_Thresh__3;
        if (Climb_Inhibit == 1U) {
          temp21 = Up_Separation + 100U;
        } else {
          temp21 = Up_Separation;
        }
        if (temp21 > Down_Separation) {
          upward_preferred_2 = 1U;
        }
        if (upward_preferred_2 == 1U) {
          if (Own_Tracked_Alt < Other_Tracked_Alt) {
            temp22 = 1U;
          } else {
            temp22 = 0U;
          }
          if (temp22 != 0U) {
            if (Cur_Vertical_Sep >= 300U) {
              if (Down_Separation >= alim_Non_Crossing_Biased_Descend) {
                result_Non_Crossing_Biased_Descend = 1U;
              }
            }
          }
        } else {
          if (Other_Tracked_Alt < Own_Tracked_Alt) {
            temp23 = 1U;
          } else {
            temp23 = 0U;
          }
          if (! (temp23 != 0U)) {
            result_Non_Crossing_Biased_Descend = 1U;
          } else {
            if (temp23 != 0U) {
              if (Up_Separation >= alim_Non_Crossing_Biased_Descend) {
                result_Non_Crossing_Biased_Descend = 1U;
              }
            }
          }
        }
        temp3 = result_Non_Crossing_Biased_Descend;
        if (Other_Tracked_Alt < Own_Tracked_Alt) {
          temp4 = 1U;
        } else {
          temp4 = 0U;
        }
        if (temp3 != 0U) {
          if (temp4 != 0U) {
            need_downward_RA = 1U;
          }
        }
        if (need_upward_RA != 0U) {
          if (need_downward_RA != 0U) {
            alt_sep = 0U;
          } else {
            goto _L;
          }
        } else {
          _L: /* CIL Label */ 
          if (need_upward_RA != 0U) {
            alt_sep = 1U;
          } else {
            if (need_downward_RA != 0U) {
              if (Up_Separation >= alim) {
                if (Down_Separation < alim) {
                  myCIL___tmp = 1;
                } else {
                  myCIL___tmp = 0;
                }
              } else {
                myCIL___tmp = 0;
              }
              alt_sep = 2U;
            } else {
              alt_sep = 0U;
            }
          }
        }
      }
    }
  }
  return;
              _SLICE(xxx);
}
}
