/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern int (printf)() ;
int main(void) 
{ int x ;
  int x___0 ;
  int x___1 ;

  {
  x = 4;
  x___0 = 6;
  printf("hi%d\n", x___0);
  x___1 = 7;
  printf("hi2 %d\n", x___1);
  printf("hello%d\n", x);
  return (0);
}
}
