SRC=recursive.clpr \
	fibonacci5.clpr \
	idempotent.clpr \
	allzero.clpr \
	reversesimple.clpr \
	fibsumto.clpr \
	solver_wrapper.clpr \
	solver_arith.clpr \
	solver_uif.clpr \
	solver_array.clpr \
	solver_ask.clpr

zip:
	zip recursive.zip ${SRC}

clean:
	rm -f *~ *.zip

