/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

int safety  ;
int s  ;
int NP  ;
int SKIP1  ;
int compRegistered  ;
extern int __VERIFIER_nondet_int() ;
extern int _SLICE() ;
void main(void) 
{ int main_tmp_ndt_1 ;
  int main_tmp_ndt_2 ;
  int main_tmp_ndt_3 ;
  int main_tmp_ndt_4 ;
  int main_tmp_ndt_5 ;
  int KbFilter_PnP_irpStack__MinorFunction ;
  int IofCallDriver_tmp_ndt_6___1 ;
  int IofCallDriver_tmp_ndt_7___1 ;
  int IofCallDriver_tmp_ndt_6___2 ;
  int IofCallDriver_tmp_ndt_7___2 ;
  int IofCallDriver_tmp_ndt_6___3 ;
  int IofCallDriver_tmp_ndt_7___3 ;
  int IofCallDriver_tmp_ndt_6___4 ;
  int IofCallDriver_tmp_ndt_7___4 ;
  int KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode ;
  int KbFilter_InternIoCtl_devExt__UpperConnectData__ClassService ;
  int KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__InputBufferLength ;
  int KbFilter_InternIoCtl_sizeof__CONNECT_DATA ;
  int KbFilter_InternIoCtl_sizeof__INTERNAL_I8042_HOOK_KEYBOARD ;
  int KbFilter_InternIoCtl_CIL___Tmp20 ;
  int KbFilter_InternIoCtl_CIL___Tmp24 ;
  int KbFilter_InternIoCtl_CIL___Tmp28 ;
  int IofCallDriver_tmp_ndt_6___5 ;
  int IofCallDriver_tmp_ndt_7___5 ;

  {
  safety = 0;
  NP = 1;
  SKIP1 = 3;
  s = NP;
  compRegistered = 0;
  main_tmp_ndt_1 = __VERIFIER_nondet_int();
  if (main_tmp_ndt_1 >= 0) {
    if (main_tmp_ndt_1 <= 0) {
      safety = safety + (s - NP);
      s = SKIP1;
      safety = safety + (s - SKIP1);
      L4: 
      if (safety != 0) goto ERROR; return; ERROR:;
    } else {
      goto _L___19;
    }
  } else {
    _L___19: ;
    if (main_tmp_ndt_1 < 0) {
      L5: 
      main_tmp_ndt_2 = __VERIFIER_nondet_int();
      if (main_tmp_ndt_2 >= 1) {
        if (main_tmp_ndt_2 <= 1) {
          safety = safety + (s - NP);
          s = SKIP1;
          safety = safety + (s - SKIP1);
          goto L4;
        } else {
          goto _L___18;
        }
      } else {
        _L___18: ;
        if (main_tmp_ndt_2 < 1) {
          L9: 
          main_tmp_ndt_3 = __VERIFIER_nondet_int();
          if (main_tmp_ndt_3 >= 3) {
            if (main_tmp_ndt_3 <= 3) {
              if (KbFilter_PnP_irpStack__MinorFunction >= 0) {
                if (KbFilter_PnP_irpStack__MinorFunction <= 0) {
                  safety = safety + (s - NP);
                  safety = safety + (compRegistered - 0);
                  safety = safety + (s - NP);
                  IofCallDriver_tmp_ndt_6___1 = __VERIFIER_nondet_int();
                  if (IofCallDriver_tmp_ndt_6___1 >= 0) {
                    if (IofCallDriver_tmp_ndt_6___1 <= 0) {
                      s = NP;
                      L10: ;
                      L11: 
                      safety = safety + (s - NP);
                      L12: ;
                      goto L4;
                    } else {
                      goto _L___0;
                    }
                  } else {
                    _L___0: ;
                    if (IofCallDriver_tmp_ndt_6___1 < 0) {
                      L14: 
                      IofCallDriver_tmp_ndt_7___1 = __VERIFIER_nondet_int();
                      if (IofCallDriver_tmp_ndt_7___1 >= 1) {
                        if (IofCallDriver_tmp_ndt_7___1 <= 1) {
                          s = NP;
                          goto L11;
                        } else {
                          goto _L;
                        }
                      } else {
                        _L: ;
                        if (IofCallDriver_tmp_ndt_7___1 < 1) {
                          L15: 
                          s = NP;
                          goto L10;
                        } else {
                          goto L15;
                        }
                      }
                    } else {
                      goto L14;
                    }
                  }
                } else {
                  goto _L___9;
                }
              } else {
                _L___9: ;
                if (KbFilter_PnP_irpStack__MinorFunction < 0) {
                  L17: 
                  safety = safety + (s - NP);
                  s = SKIP1;
                  IofCallDriver_tmp_ndt_6___2 = __VERIFIER_nondet_int();
                  if (IofCallDriver_tmp_ndt_6___2 >= 0) {
                    if (IofCallDriver_tmp_ndt_6___2 <= 0) {
                      L18: 
                      safety = safety + (s - SKIP1);
                      goto L12;
                    } else {
                      goto _L___2;
                    }
                  } else {
                    _L___2: ;
                    if (IofCallDriver_tmp_ndt_6___2 < 0) {
                      L19: 
                      IofCallDriver_tmp_ndt_7___2 = __VERIFIER_nondet_int();
                      if (IofCallDriver_tmp_ndt_7___2 >= 1) {
                        if (IofCallDriver_tmp_ndt_7___2 <= 1) {
                          goto L18;
                        } else {
                          goto _L___1;
                        }
                      } else {
                        _L___1: ;
                        if (IofCallDriver_tmp_ndt_7___2 < 1) {
                          L20: ;
                          goto L18;
                        } else {
                          goto L20;
                        }
                      }
                    } else {
                      goto L19;
                    }
                  }
                } else {
                  if (KbFilter_PnP_irpStack__MinorFunction >= 23) {
                    if (KbFilter_PnP_irpStack__MinorFunction <= 23) {
                      safety = safety + (s - NP);
                      s = SKIP1;
                      IofCallDriver_tmp_ndt_6___3 = __VERIFIER_nondet_int();
                      if (IofCallDriver_tmp_ndt_6___3 >= 0) {
                        if (IofCallDriver_tmp_ndt_6___3 <= 0) {
                          L21: 
                          safety = safety + (s - SKIP1);
                          goto L12;
                        } else {
                          goto _L___4;
                        }
                      } else {
                        _L___4: ;
                        if (IofCallDriver_tmp_ndt_6___3 < 0) {
                          L22: 
                          IofCallDriver_tmp_ndt_7___3 = __VERIFIER_nondet_int();
                          if (IofCallDriver_tmp_ndt_7___3 >= 1) {
                            if (IofCallDriver_tmp_ndt_7___3 <= 1) {
                              goto L21;
                            } else {
                              goto _L___3;
                            }
                          } else {
                            _L___3: ;
                            if (IofCallDriver_tmp_ndt_7___3 < 1) {
                              L23: ;
                              goto L21;
                            } else {
                              goto L23;
                            }
                          }
                        } else {
                          goto L22;
                        }
                      }
                    } else {
                      goto _L___8;
                    }
                  } else {
                    _L___8: ;
                    if (KbFilter_PnP_irpStack__MinorFunction < 23) {
                      L24: ;
                      if (KbFilter_PnP_irpStack__MinorFunction >= 2) {
                        if (KbFilter_PnP_irpStack__MinorFunction <= 2) {
                          safety = safety + (s - NP);
                          s = SKIP1;
                          IofCallDriver_tmp_ndt_6___4 = __VERIFIER_nondet_int();
                          if (IofCallDriver_tmp_ndt_6___4 >= 0) {
                            if (IofCallDriver_tmp_ndt_6___4 <= 0) {
                              L25: 
                              safety = safety + (s - SKIP1);
                              goto L12;
                            } else {
                              goto _L___6;
                            }
                          } else {
                            _L___6: ;
                            if (IofCallDriver_tmp_ndt_6___4 < 0) {
                              L26: 
                              IofCallDriver_tmp_ndt_7___4 = __VERIFIER_nondet_int();
                              if (IofCallDriver_tmp_ndt_7___4 >= 1) {
                                if (IofCallDriver_tmp_ndt_7___4 <= 1) {
                                  goto L25;
                                } else {
                                  goto _L___5;
                                }
                              } else {
                                _L___5: ;
                                if (IofCallDriver_tmp_ndt_7___4 < 1) {
                                  L27: ;
                                  goto L25;
                                } else {
                                  goto L27;
                                }
                              }
                            } else {
                              goto L26;
                            }
                          }
                        } else {
                          goto _L___7;
                        }
                      } else {
                        _L___7: ;
                        if (KbFilter_PnP_irpStack__MinorFunction < 2) {
                          goto L17;
                        } else {
                          goto L17;
                        }
                      }
                    } else {
                      goto L24;
                    }
                  }
                }
              }
            } else {
              goto _L___17;
            }
          } else {
            _L___17: ;
            if (main_tmp_ndt_3 < 3) {
              L28: 
              main_tmp_ndt_4 = __VERIFIER_nondet_int();
              if (main_tmp_ndt_4 >= 4) {
                if (main_tmp_ndt_4 <= 4) {
                  safety = safety + (s - NP);
                  s = SKIP1;
                  safety = safety + (s - SKIP1);
                  goto L4;
                } else {
                  goto _L___16;
                }
              } else {
                _L___16: ;
                if (main_tmp_ndt_4 < 4) {
                  L31: 
                  main_tmp_ndt_5 = __VERIFIER_nondet_int();
                  if (main_tmp_ndt_5 >= 8) {
                    if (main_tmp_ndt_5 <= 8) {
                      if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode >= KbFilter_InternIoCtl_CIL___Tmp20) {
                        if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode <= KbFilter_InternIoCtl_CIL___Tmp20) {
                          if (KbFilter_InternIoCtl_devExt__UpperConnectData__ClassService > 0) {
                            L32: ;
                            L33: 
                            safety = safety + (s - NP);
                            L34: ;
                            goto L4;
                          } else {
                            if (KbFilter_InternIoCtl_devExt__UpperConnectData__ClassService < 0) {
                              goto L32;
                            } else {
                              if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__InputBufferLength < KbFilter_InternIoCtl_sizeof__CONNECT_DATA) {
                                L35: ;
                                goto L33;
                              } else {
                                L36: 
                                safety = safety + (s - NP);
                                s = SKIP1;
                                IofCallDriver_tmp_ndt_6___5 = __VERIFIER_nondet_int();
                                if (IofCallDriver_tmp_ndt_6___5 >= 0) {
                                  if (IofCallDriver_tmp_ndt_6___5 <= 0) {
                                    L37: 
                                    safety = safety + (s - SKIP1);
                                    goto L34;
                                  } else {
                                    goto _L___11;
                                  }
                                } else {
                                  _L___11: ;
                                  if (IofCallDriver_tmp_ndt_6___5 < 0) {
                                    L38: 
                                    IofCallDriver_tmp_ndt_7___5 = __VERIFIER_nondet_int();
                                    if (IofCallDriver_tmp_ndt_7___5 >= 1) {
                                      if (IofCallDriver_tmp_ndt_7___5 <= 1) {
                                        goto L37;
                                      } else {
                                        goto _L___10;
                                      }
                                    } else {
                                      _L___10: ;
                                      if (IofCallDriver_tmp_ndt_7___5 < 1) {
                                        L39: ;
                                        goto L37;
                                      } else {
                                        goto L39;
                                      }
                                    }
                                  } else {
                                    goto L38;
                                  }
                                }
                              }
                            }
                          }
                        } else {
                          goto _L___14;
                        }
                      } else {
                        _L___14: ;
                        if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode < KbFilter_InternIoCtl_CIL___Tmp20) {
                          L40: ;
                          if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode >= KbFilter_InternIoCtl_CIL___Tmp24) {
                            if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode <= KbFilter_InternIoCtl_CIL___Tmp24) {
                              goto L33;
                            } else {
                              goto _L___13;
                            }
                          } else {
                            _L___13: ;
                            if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode < KbFilter_InternIoCtl_CIL___Tmp24) {
                              L41: ;
                              if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode >= KbFilter_InternIoCtl_CIL___Tmp28) {
                                if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode <= KbFilter_InternIoCtl_CIL___Tmp28) {
                                  if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__InputBufferLength < KbFilter_InternIoCtl_sizeof__INTERNAL_I8042_HOOK_KEYBOARD) {
                                    goto L35;
                                  } else {
                                    goto L36;
                                  }
                                } else {
                                  goto _L___12;
                                }
                              } else {
                                _L___12: ;
                                if (KbFilter_InternIoCtl_irpStack__Parameters__DeviceIoControl__IoControlCode < KbFilter_InternIoCtl_CIL___Tmp28) {
                                  goto L36;
                                } else {
                                  goto L36;
                                }
                              }
                            } else {
                              goto L41;
                            }
                          }
                        } else {
                          goto L40;
                        }
                      }
                    } else {
                      goto _L___15;
                    }
                  } else {
                    _L___15: ;
                    if (main_tmp_ndt_5 < 8) {
                      goto L4;
                    } else {
                      goto L4;
                    }
                  }
                } else {
                  goto L31;
                }
              }
            } else {
              goto L28;
            }
          }
        } else {
          goto L9;
        }
      }
    } else {
      goto L5;
    }
  }
  return;
}
}
