/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

int FloppyThread  ;
int KernelMode  ;
int Suspended  ;
int Executive  ;
int DiskController  ;
int FloppyDiskPeripheral  ;
int FlConfigCallBack  ;
int MaximumInterfaceType  ;
int MOUNTDEV_MOUNTED_DEVICE_GUID  ;
int myStatus  ;
int s  ;
int UNLOADED  ;
int NP  ;
int DC  ;
int SKIP1  ;
int SKIP2  ;
int MPR1  ;
int MPR3  ;
int IPC  ;
int pended  ;
int compRegistered  ;
int lowerDriverReturn  ;
int setEventCalled  ;
int customIrp  ;
int safety  ;
void _BLAST_init(void) 
{ 

  {
    UNLOADED = 0;
    NP = 1;
    DC = 2;
    SKIP1 = 3;
    SKIP2 = 4;
    MPR1 = 5;
    MPR3 = 6;
    IPC = 7;
    s = UNLOADED;
    pended = 0;
    compRegistered = 0;
    lowerDriverReturn = 0;
    setEventCalled = 0;
    customIrp = 0;

    return;
  }
}
int PagingReferenceCount  =    0;
int PagingMutex  =    0;
int FlAcpiConfigureFloppy(int FlAcpiConfigureFloppy_DisketteExtension , int FlAcpiConfigureFloppy_FdcInfo ) 
{ int retres3 ;

  {
    retres3 = 0;
    return (retres3);
  }
}
int PsCreateSystemThread(int PsCreateSystemThread_ThreadHandle , int PsCreateSystemThread_DesiredAccess , int PsCreateSystemThread_ObjectAttributes , int PsCreateSystemThread_ProcessHandle , int PsCreateSystemThread_ClientId , int PsCreateSystemThread_StartRoutine , int PsCreateSystemThread_StartContext ) ;
int ObReferenceObjectByHandle(int ObReferenceObjectByHandle_Handle , int ObReferenceObjectByHandle_DesiredAccess , int ObReferenceObjectByHandle_ObjectType , int ObReferenceObjectByHandle_AccessMode , int ObReferenceObjectByHandle_Object , int ObReferenceObjectByHandle_HandleInformation ) ;
int ZwClose(int ZwClose_Handle ) ;
int FlQueueIrpToThread(int FlQueueIrpToThread_Irp , int FlQueueIrpToThread_DisketteExtension ) 
{ int FlQueueIrpToThread_status ;
  int FlQueueIrpToThread_threadHandle ;
  int FlQueueIrpToThread_DisketteExtension__PoweringDown ;
  int FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount ;
  int FlQueueIrpToThread_DisketteExtension__FloppyThread ;
  int FlQueueIrpToThread_Irp__IoStatus__Status ;
  int FlQueueIrpToThread_Irp__IoStatus__Information ;
  int FlQueueIrpToThread_ObjAttributes ;
  int retres11 ;
  int TRACER_returning ;

  {
    TRACER_returning = 0;
    if ((FlQueueIrpToThread_DisketteExtension__PoweringDown >= 1) && (FlQueueIrpToThread_DisketteExtension__PoweringDown <= 1)) {
      myStatus = -1073741101;
      FlQueueIrpToThread_Irp__IoStatus__Status = -1073741101;
      FlQueueIrpToThread_Irp__IoStatus__Information = 0;
      retres11 = -1073741101;
    }
    else {
      FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount = FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount + 1;
      if ((FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount >= 0) && (FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount <= 0)) {
        FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount = FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount + 1;
        PagingReferenceCount = PagingReferenceCount + 1;
        if ((PagingReferenceCount >= 1) && (PagingReferenceCount <= 1)) {

        }
        FlQueueIrpToThread_status = PsCreateSystemThread(FlQueueIrpToThread_threadHandle, 0, FlQueueIrpToThread_ObjAttributes, 0, 0, FloppyThread, FlQueueIrpToThread_DisketteExtension);
        if (FlQueueIrpToThread_status < 0) {
          FlQueueIrpToThread_DisketteExtension__ThreadReferenceCount = -1;
          PagingReferenceCount = PagingReferenceCount - 1;
          if ((PagingReferenceCount >= 0) && (PagingReferenceCount <= 0)) {

          }
          retres11 = FlQueueIrpToThread_status;
          TRACER_returning = 1;
        }
        else {
          FlQueueIrpToThread_status = ObReferenceObjectByHandle(FlQueueIrpToThread_threadHandle, 1048576, 0, KernelMode, FlQueueIrpToThread_DisketteExtension__FloppyThread, 0);
          ZwClose(FlQueueIrpToThread_threadHandle);
          if (FlQueueIrpToThread_status < 0) {
            retres11 = FlQueueIrpToThread_status;
            TRACER_returning = 1;
          }
        }
      }
      if (TRACER_returning <= 0) {
        safety = safety + (pended - 0);
        pended = 1;
        retres11 = 259;
      }
    }
    return (retres11);
  }
}
void IofCompleteRequest(int IofCompleteRequest_Irp , int IofCompleteRequest_PriorityBoost ) ;
int FloppyStartDevice(int FloppyStartDevice_DeviceObject , int FloppyStartDevice_Irp ) ;
int IofCallDriver(int IofCallDriver_DeviceObject , int IofCallDriver_Irp ) ;
int KeWaitForSingleObject(int KeWaitForSingleObject_Object , int KeWaitForSingleObject_WaitReason , int KeWaitForSingleObject_WaitMode , int KeWaitForSingleObject_Alertable , int KeWaitForSingleObject_Timeout ) ;
int IoSetDeviceInterfaceState(int IoSetDeviceInterfaceState_SymbolicLinkName , int IoSetDeviceInterfaceState_Enable ) ;
int IoDeleteSymbolicLink(int IoDeleteSymbolicLink_SymbolicLinkName ) ;
int FloppyPnp(int FloppyPnp_DeviceObject , int FloppyPnp_Irp ) 
{ int FloppyPnp_DeviceObject__DeviceExtension ;
  int FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation ;
  int FloppyPnp_Irp__IoStatus__Information ;
  int FloppyPnp_Irp__IoStatus__Status ;
  int FloppyPnp_Irp__CurrentLocation ;
  int FloppyPnp_disketteExtension__IsRemoved ;
  int FloppyPnp_disketteExtension__IsStarted ;
  int FloppyPnp_disketteExtension__TargetObject ;
  int FloppyPnp_disketteExtension__HoldNewRequests ;
  int FloppyPnp_disketteExtension__FloppyThread ;
  int FloppyPnp_disketteExtension__InterfaceString__Buffer ;
  int FloppyPnp_disketteExtension__InterfaceString ;
  int FloppyPnp_disketteExtension__ArcName__Length ;
  int FloppyPnp_disketteExtension__ArcName ;
  int FloppyPnp_irpSp__MinorFunction ;
  int FloppyPnp_IoGetConfigurationInformation__FloppyCount ;
  int FloppyPnp_irpSp ;
  int FloppyPnp_disketteExtension ;
  int FloppyPnp_ntStatus ;
  int FloppyPnp_doneEvent ;
  int FloppyPnp_irpSp___0 ;
  int FloppyPnp_nextIrpSp ;
  int FloppyPnp_nextIrpSp__Control ;
  int FloppyPnp_irpSp___1 ;
  int FloppyPnp_irpSp__Context ;
  int FloppyPnp_irpSp__Control ;
  int FloppyPnp_CIL___Tmp29 ;
  int FloppyPnp_CIL___Tmp30 ;
  int retres31 ;
  int TRACER_returning ;

  {
    TRACER_returning = 0;
    FloppyPnp_ntStatus = 0;
    PagingReferenceCount = PagingReferenceCount + 1;
    if ((PagingReferenceCount >= 1) && (PagingReferenceCount <= 1)) {

    }
    FloppyPnp_disketteExtension = FloppyPnp_DeviceObject__DeviceExtension;
    FloppyPnp_irpSp = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation;
    if ((FloppyPnp_disketteExtension__IsRemoved > 0) || (FloppyPnp_disketteExtension__IsRemoved < 0)) {
      FloppyPnp_Irp__IoStatus__Information = 0;
      FloppyPnp_Irp__IoStatus__Status = -1073741738;
      myStatus = -1073741738;
      IofCompleteRequest(FloppyPnp_Irp, 0);
      retres31 = -1073741738;
    }
    else {
      if ((FloppyPnp_irpSp__MinorFunction >= 0) && (FloppyPnp_irpSp__MinorFunction <= 0)) {
        FloppyPnp_ntStatus = FloppyStartDevice(FloppyPnp_DeviceObject, FloppyPnp_Irp);
      } else {
        if ((FloppyPnp_irpSp__MinorFunction >= 5) && (FloppyPnp_irpSp__MinorFunction <= 5)) {
          if ((FloppyPnp_irpSp__MinorFunction >= 5) && (FloppyPnp_irpSp__MinorFunction <= 5)) {

          }
          if ((FloppyPnp_disketteExtension__IsStarted >= 0) && (FloppyPnp_disketteExtension__IsStarted <= 0)) {
            safety = safety + (s - NP);
            s = SKIP1;
            FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
            FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
            FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
            retres31 = FloppyPnp_ntStatus;
            TRACER_returning = 1;
          }
          else {
            FloppyPnp_disketteExtension__HoldNewRequests = 1;
            FloppyPnp_ntStatus = FlQueueIrpToThread(FloppyPnp_Irp, FloppyPnp_disketteExtension);
            FloppyPnp_CIL___Tmp29 = FloppyPnp_ntStatus;
            if ((FloppyPnp_CIL___Tmp29 >= 259) && (FloppyPnp_CIL___Tmp29 <= 259)) {
              KeWaitForSingleObject(FloppyPnp_disketteExtension__FloppyThread, Executive, KernelMode, 0, 0);
              if ((FloppyPnp_disketteExtension__FloppyThread > 0) || (FloppyPnp_disketteExtension__FloppyThread < 0)) {

              }
              FloppyPnp_disketteExtension__FloppyThread = 0;
              FloppyPnp_Irp__IoStatus__Status = 0;
              myStatus = 0;
              safety = safety + (s - NP);
              s = SKIP1;
              FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
              FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
              FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
            } else {
              FloppyPnp_ntStatus = -1073741823;
              FloppyPnp_Irp__IoStatus__Status = FloppyPnp_ntStatus;
              myStatus = FloppyPnp_ntStatus;
              FloppyPnp_Irp__IoStatus__Information = 0;
              IofCompleteRequest(FloppyPnp_Irp, 0);
            }
          }
        } else {
          if ((FloppyPnp_irpSp__MinorFunction >= 1) && (FloppyPnp_irpSp__MinorFunction <= 1)) {
            if ((FloppyPnp_irpSp__MinorFunction >= 5) && (FloppyPnp_irpSp__MinorFunction <= 5)) {

            }
            if ((FloppyPnp_disketteExtension__IsStarted >= 0) && (FloppyPnp_disketteExtension__IsStarted <= 0)) {
              safety = safety + (s - NP);
              s = SKIP1;
              FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
              FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
              FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
              retres31 = FloppyPnp_ntStatus;
              TRACER_returning = 1;
            }
            else {
              FloppyPnp_disketteExtension__HoldNewRequests = 1;
              FloppyPnp_ntStatus = FlQueueIrpToThread(FloppyPnp_Irp, FloppyPnp_disketteExtension);
              FloppyPnp_CIL___Tmp29 = FloppyPnp_ntStatus;
              if ((FloppyPnp_CIL___Tmp29 >= 259) && (FloppyPnp_CIL___Tmp29 <= 259)) {
                KeWaitForSingleObject(FloppyPnp_disketteExtension__FloppyThread, Executive, KernelMode, 0, 0);
                if ((FloppyPnp_disketteExtension__FloppyThread > 0) || (FloppyPnp_disketteExtension__FloppyThread < 0)) {

                }
                FloppyPnp_disketteExtension__FloppyThread = 0;
                FloppyPnp_Irp__IoStatus__Status = 0;
                myStatus = 0;
                safety = safety + (s - NP);
                s = SKIP1;
                FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
                FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
                FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
              } else {
                FloppyPnp_ntStatus = -1073741823;
                FloppyPnp_Irp__IoStatus__Status = FloppyPnp_ntStatus;
                myStatus = FloppyPnp_ntStatus;
                FloppyPnp_Irp__IoStatus__Information = 0;
                IofCompleteRequest(FloppyPnp_Irp, 0);
              }
            }
          } else {
            if ((FloppyPnp_irpSp__MinorFunction >= 6) && (FloppyPnp_irpSp__MinorFunction <= 6)) {
              if ((FloppyPnp_irpSp__MinorFunction >= 6) && (FloppyPnp_irpSp__MinorFunction <= 6)) {

              }
              if ((FloppyPnp_disketteExtension__IsStarted >= 0) && (FloppyPnp_disketteExtension__IsStarted <= 0)) {
                FloppyPnp_Irp__IoStatus__Status = 0;
                myStatus = 0;
                safety = safety + (s - NP);
                s = SKIP1;
                FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
                FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
                FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
              } else {
                FloppyPnp_Irp__IoStatus__Status = 0;
                myStatus = 0;
                FloppyPnp_irpSp___0 = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation;
                FloppyPnp_nextIrpSp = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation - 1;
                FloppyPnp_nextIrpSp__Control = 0;
                safety = safety + (s - NP);
                safety = safety + (compRegistered - 0);
                compRegistered = 1;
                FloppyPnp_irpSp___1 = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation - 1;
                FloppyPnp_irpSp__Context = FloppyPnp_doneEvent;
                FloppyPnp_irpSp__Control = 224;
                FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
                FloppyPnp_CIL___Tmp30 = FloppyPnp_ntStatus;
                if ((FloppyPnp_CIL___Tmp30 >= 259) && (FloppyPnp_CIL___Tmp30 <= 259)) {
                  KeWaitForSingleObject(FloppyPnp_doneEvent, Executive, KernelMode, 0, 0);
                  FloppyPnp_ntStatus = myStatus;
                }
                FloppyPnp_disketteExtension__HoldNewRequests = 0;
                FloppyPnp_Irp__IoStatus__Status = FloppyPnp_ntStatus;
                myStatus = FloppyPnp_ntStatus;
                FloppyPnp_Irp__IoStatus__Information = 0;
                IofCompleteRequest(FloppyPnp_Irp, 0);
              }
            } else {
              if ((FloppyPnp_irpSp__MinorFunction >= 3) && (FloppyPnp_irpSp__MinorFunction <= 3)) {
                if ((FloppyPnp_irpSp__MinorFunction >= 6) && (FloppyPnp_irpSp__MinorFunction <= 6)) {

                }
                if ((FloppyPnp_disketteExtension__IsStarted >= 0) && (FloppyPnp_disketteExtension__IsStarted <= 0)) {
                  FloppyPnp_Irp__IoStatus__Status = 0;
                  myStatus = 0;
                  safety = safety + (s - NP);
                  s = SKIP1;
                  FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
                  FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
                  FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
                } else {
                  FloppyPnp_Irp__IoStatus__Status = 0;
                  myStatus = 0;
                  FloppyPnp_irpSp___0 = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation;
                  FloppyPnp_nextIrpSp = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation - 1;
                  FloppyPnp_nextIrpSp__Control = 0;
                  safety = safety + (s - NP);
                  safety = safety + (compRegistered - 0);
                  compRegistered = 1;
                  FloppyPnp_irpSp___1 = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation - 1;
                  FloppyPnp_irpSp__Context = FloppyPnp_doneEvent;
                  FloppyPnp_irpSp__Control = 224;
                  FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
                  FloppyPnp_CIL___Tmp30 = FloppyPnp_ntStatus;
                  if ((FloppyPnp_CIL___Tmp30 >= 259) && (FloppyPnp_CIL___Tmp30 <= 259)) {
                    KeWaitForSingleObject(FloppyPnp_doneEvent, Executive, KernelMode, 0, 0);
                    FloppyPnp_ntStatus = myStatus;
                  }
                  FloppyPnp_disketteExtension__HoldNewRequests = 0;
                  FloppyPnp_Irp__IoStatus__Status = FloppyPnp_ntStatus;
                  myStatus = FloppyPnp_ntStatus;
                  FloppyPnp_Irp__IoStatus__Information = 0;
                  IofCompleteRequest(FloppyPnp_Irp, 0);
                }
              } else {
                if ((FloppyPnp_irpSp__MinorFunction >= 4) && (FloppyPnp_irpSp__MinorFunction <= 4)) {
                  FloppyPnp_disketteExtension__IsStarted = 0;
                  FloppyPnp_Irp__IoStatus__Status = 0;
                  myStatus = 0;
                  safety = safety + (s - NP);
                  s = SKIP1;
                  FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
                  FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
                  FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
                } else {
                  if ((FloppyPnp_irpSp__MinorFunction >= 2) && (FloppyPnp_irpSp__MinorFunction <= 2)) {
                    FloppyPnp_disketteExtension__HoldNewRequests = 0;
                    FloppyPnp_disketteExtension__IsStarted = 0;
                    FloppyPnp_disketteExtension__IsRemoved = 1;
                    safety = safety + (s - NP);
                    s = SKIP1;
                    FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
                    FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
                    FloppyPnp_Irp__IoStatus__Status = 0;
                    myStatus = 0;
                    FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
                    if ((FloppyPnp_disketteExtension__InterfaceString__Buffer > 0) || (FloppyPnp_disketteExtension__InterfaceString__Buffer < 0)) {
                      IoSetDeviceInterfaceState(FloppyPnp_disketteExtension__InterfaceString, 0);
                    }
                    if ((FloppyPnp_disketteExtension__ArcName__Length > 0) || (FloppyPnp_disketteExtension__ArcName__Length < 0)) {
                      IoDeleteSymbolicLink(FloppyPnp_disketteExtension__ArcName);
                    }
                    FloppyPnp_IoGetConfigurationInformation__FloppyCount = FloppyPnp_IoGetConfigurationInformation__FloppyCount - 1;
                  } else {
                    safety = safety + (s - NP);
                    s = SKIP1;
                    FloppyPnp_Irp__CurrentLocation = FloppyPnp_Irp__CurrentLocation + 1;
                    FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation = FloppyPnp_Irp__Tail__Overlay__CurrentStackLocation + 1;
                    FloppyPnp_ntStatus = IofCallDriver(FloppyPnp_disketteExtension__TargetObject, FloppyPnp_Irp);
                  }
                }
              }
            }
          }
        }
      }
      if (TRACER_returning <= 0) {
        PagingReferenceCount = PagingReferenceCount - 1;
        if ((PagingReferenceCount >= 0) && (PagingReferenceCount <= 0)) {

        }
        retres31 = FloppyPnp_ntStatus;
      }
    }
    return (retres31);
  }
}
int FlFdcDeviceIo(int FlFdcDeviceIo_DeviceObject , int FlFdcDeviceIo_Ioctl , int FlFdcDeviceIo_Data ) ;
extern int uninf1() ;
int IoQueryDeviceDescription(int IoQueryDeviceDescription_BusType , int IoQueryDeviceDescription_BusNumber , int IoQueryDeviceDescription_ControllerType , int IoQueryDeviceDescription_ControllerNumber , int IoQueryDeviceDescription_PeripheralType , int IoQueryDeviceDescription_PeripheralNumber , int IoQueryDeviceDescription_CalloutRoutine , int IoQueryDeviceDescription_Context ) ;
int IoRegisterDeviceInterface(int IoRegisterDeviceInterface_PhysicalDeviceObject , int IoRegisterDeviceInterface_InterfaceClassGuid , int IoRegisterDeviceInterface_ReferenceString , int IoRegisterDeviceInterface_SymbolicLinkName ) ;
int FloppyStartDevice(int FloppyStartDevice_DeviceObject , int FloppyStartDevice_Irp ) 
{ int FloppyStartDevice_DeviceObject__DeviceExtension ;
  int FloppyStartDevice_Irp__Tail__Overlay__CurrentStackLocation ;
  int FloppyStartDevice_Irp__IoStatus__Status ;
  int FloppyStartDevice_disketteExtension__TargetObject ;
  int FloppyStartDevice_disketteExtension__MaxTransferSize ;
  int FloppyStartDevice_disketteExtension__DriveType ;
  int FloppyStartDevice_disketteExtension__DeviceUnit ;
  int FloppyStartDevice_disketteExtension__UnderlyingPDO ;
  int FloppyStartDevice_disketteExtension__InterfaceString ;
  int FloppyStartDevice_disketteExtension__IsStarted ;
  int FloppyStartDevice_disketteExtension__HoldNewRequests ;
  int FloppyStartDevice_ntStatus ;
  int FloppyStartDevice_pnpStatus ;
  int FloppyStartDevice_doneEvent ;
  int FloppyStartDevice_fdcInfo ;
  int FloppyStartDevice_fdcInfo__BufferCount ;
  int FloppyStartDevice_fdcInfo__BufferSize ;
  int FloppyStartDevice_fdcInfo__MaxTransferSize ;
  int FloppyStartDevice_fdcInfo__AcpiBios ;
  int FloppyStartDevice_fdcInfo__AcpiFdiSupported ;
  int FloppyStartDevice_fdcInfo__PeripheralNumber ;
  int FloppyStartDevice_fdcInfo__UnitNumber ;
  int FloppyStartDevice_Dc ;
  int FloppyStartDevice_Fp ;
  int FloppyStartDevice_disketteExtension ;
  int FloppyStartDevice_irpSp ;
  int FloppyStartDevice_irpSp___0 ;
  int FloppyStartDevice_nextIrpSp ;
  int FloppyStartDevice_nextIrpSp__Control ;
  int FloppyStartDevice_irpSp___1 ;
  int FloppyStartDevice_irpSp__Control ;
  int FloppyStartDevice_irpSp__Context ;
  int FloppyStartDevice_InterfaceType ;
  int FloppyStartDevice_KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86 ;
  int FloppyStartDevice_CIL___Tmp42 ;
  int FloppyStartDevice_CIL___Tmp43 ;
  int FloppyStartDevice_CIL___Tmp44 ;
  int FloppyStartDevice_CIL___Tmp45 ;
  int FloppyStartDevice_CIL___Tmp46 ;
  int FloppyStartDevice_CIL___Tmp47 ;
  int FloppyStartDevice_CIL___Tmp48 ;

  {
    FloppyStartDevice_Dc = DiskController;
    FloppyStartDevice_Fp = FloppyDiskPeripheral;
    FloppyStartDevice_disketteExtension = FloppyStartDevice_DeviceObject__DeviceExtension;
    FloppyStartDevice_irpSp = FloppyStartDevice_Irp__Tail__Overlay__CurrentStackLocation;
    FloppyStartDevice_irpSp___0 = FloppyStartDevice_Irp__Tail__Overlay__CurrentStackLocation;
    FloppyStartDevice_nextIrpSp = FloppyStartDevice_Irp__Tail__Overlay__CurrentStackLocation - 1;
    FloppyStartDevice_nextIrpSp__Control = 0;
    safety = safety + (s - NP);
    safety = safety + (compRegistered - 0);
    compRegistered = 1;
    FloppyStartDevice_irpSp___1 = FloppyStartDevice_Irp__Tail__Overlay__CurrentStackLocation - 1;
    FloppyStartDevice_irpSp__Context = FloppyStartDevice_doneEvent;
    FloppyStartDevice_irpSp__Control = 224;
    FloppyStartDevice_ntStatus = IofCallDriver(FloppyStartDevice_disketteExtension__TargetObject, FloppyStartDevice_Irp);
    FloppyStartDevice_CIL___Tmp42 = FloppyStartDevice_ntStatus;
    if ((FloppyStartDevice_CIL___Tmp42 >= 259) && (FloppyStartDevice_CIL___Tmp42 <= 259)) {
      FloppyStartDevice_ntStatus = KeWaitForSingleObject(FloppyStartDevice_doneEvent, Executive, KernelMode, 0, 0);
      FloppyStartDevice_ntStatus = myStatus;
    }
    FloppyStartDevice_fdcInfo__BufferCount = 0;
    FloppyStartDevice_fdcInfo__BufferSize = 0;
    FloppyStartDevice_CIL___Tmp43 = 3080;
    FloppyStartDevice_CIL___Tmp44 = 458752;
    FloppyStartDevice_CIL___Tmp45 = 461832;
    FloppyStartDevice_CIL___Tmp46 = 461835;
    FloppyStartDevice_ntStatus = FlFdcDeviceIo(FloppyStartDevice_disketteExtension__TargetObject, FloppyStartDevice_CIL___Tmp46, FloppyStartDevice_fdcInfo);
    if (FloppyStartDevice_ntStatus >= 0) {
      FloppyStartDevice_disketteExtension__MaxTransferSize = FloppyStartDevice_fdcInfo__MaxTransferSize;
      if ((FloppyStartDevice_fdcInfo__AcpiBios > 0) || (FloppyStartDevice_fdcInfo__AcpiBios < 0)) {
        if ((FloppyStartDevice_fdcInfo__AcpiFdiSupported > 0) || (FloppyStartDevice_fdcInfo__AcpiFdiSupported < 0)) {
          FloppyStartDevice_ntStatus = FlAcpiConfigureFloppy(FloppyStartDevice_disketteExtension, FloppyStartDevice_fdcInfo);
          if ((FloppyStartDevice_disketteExtension__DriveType >= 4) && (FloppyStartDevice_disketteExtension__DriveType <= 4)) {
            FloppyStartDevice_CIL___Tmp47 = uninf1();
          }
        } else {
          if ((FloppyStartDevice_disketteExtension__DriveType >= 4) && (FloppyStartDevice_disketteExtension__DriveType <= 4)) {
            FloppyStartDevice_CIL___Tmp48 = uninf1();
          }
          FloppyStartDevice_InterfaceType = 0;
        }
      } else {
        if ((FloppyStartDevice_disketteExtension__DriveType >= 4) && (FloppyStartDevice_disketteExtension__DriveType <= 4)) {
          FloppyStartDevice_CIL___Tmp48 = uninf1();
        }
        FloppyStartDevice_InterfaceType = 0;
      }
      if (FloppyStartDevice_ntStatus >= 0) {
        if ((FloppyStartDevice_KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86 > 0) || (FloppyStartDevice_KUSER_SHARED_DATA__AlternativeArchitecture_NEC98x86 < 0)) {
          FloppyStartDevice_disketteExtension__DeviceUnit = FloppyStartDevice_fdcInfo__UnitNumber;
        } else {
          FloppyStartDevice_disketteExtension__DeviceUnit = FloppyStartDevice_fdcInfo__PeripheralNumber;
        }
        FloppyStartDevice_pnpStatus = IoRegisterDeviceInterface(FloppyStartDevice_disketteExtension__UnderlyingPDO, MOUNTDEV_MOUNTED_DEVICE_GUID, 0, FloppyStartDevice_disketteExtension__InterfaceString);
        if (FloppyStartDevice_pnpStatus >= 0) {
          FloppyStartDevice_pnpStatus = IoSetDeviceInterfaceState(FloppyStartDevice_disketteExtension__InterfaceString, 1);
        }
        FloppyStartDevice_disketteExtension__IsStarted = 1;
        FloppyStartDevice_disketteExtension__HoldNewRequests = 0;
      }
    }
    FloppyStartDevice_Irp__IoStatus__Status = FloppyStartDevice_ntStatus;
    myStatus = FloppyStartDevice_ntStatus;
    IofCompleteRequest(FloppyStartDevice_Irp, 0);
    return (FloppyStartDevice_ntStatus);
  }
}
int KeSetEvent(int KeSetEvent_Event , int KeSetEvent_Increment , int KeSetEvent_Wait ) ;
int FloppyPnpComplete(int FloppyPnpComplete_DeviceObject , int FloppyPnpComplete_Irp , int FloppyPnpComplete_Context ) 
{ int retres4 ;

  {
    KeSetEvent(FloppyPnpComplete_Context, 1, 0);
    retres4 = -1073741802;
    return (retres4);
  }
}
int IoBuildDeviceIoControlRequest(int IoBuildDeviceIoControlRequest_IoControlCode , int IoBuildDeviceIoControlRequest_DeviceObject , int IoBuildDeviceIoControlRequest_InputBuffer , int IoBuildDeviceIoControlRequest_InputBufferLength , int IoBuildDeviceIoControlRequest_OutputBuffer , int IoBuildDeviceIoControlRequest_OutputBufferLength , int IoBuildDeviceIoControlRequest_InternalDeviceIoControl , int IoBuildDeviceIoControlRequest_Event , int IoBuildDeviceIoControlRequest_IoStatusBlock ) ;
int FlFdcDeviceIo(int FlFdcDeviceIo_DeviceObject , int FlFdcDeviceIo_Ioctl , int FlFdcDeviceIo_Data ) 
{ int FlFdcDeviceIo_ntStatus ;
  int FlFdcDeviceIo_irp ;
  int FlFdcDeviceIo_irpStack ;
  int FlFdcDeviceIo_doneEvent ;
  int FlFdcDeviceIo_ioStatus ;
  int FlFdcDeviceIo_irp__Tail__Overlay__CurrentStackLocation ;
  int FlFdcDeviceIo_irpStack__Parameters__DeviceIoControl__Type3InputBuffer ;
  int FlFdcDeviceIo_CIL___Tmp11 ;
  int retres12 ;

  {
    FlFdcDeviceIo_irp = IoBuildDeviceIoControlRequest(FlFdcDeviceIo_Ioctl, FlFdcDeviceIo_DeviceObject, 0, 0, 0, 0, 1, FlFdcDeviceIo_doneEvent, FlFdcDeviceIo_ioStatus);
    if ((FlFdcDeviceIo_irp >= 0) && (FlFdcDeviceIo_irp <= 0)) {
      retres12 = -1073741670;
    }
    else {
      FlFdcDeviceIo_irpStack = FlFdcDeviceIo_irp__Tail__Overlay__CurrentStackLocation - 1;
      FlFdcDeviceIo_irpStack__Parameters__DeviceIoControl__Type3InputBuffer = FlFdcDeviceIo_Data;
      FlFdcDeviceIo_ntStatus = IofCallDriver(FlFdcDeviceIo_DeviceObject, FlFdcDeviceIo_irp);
      FlFdcDeviceIo_CIL___Tmp11 = FlFdcDeviceIo_ntStatus;
      if ((FlFdcDeviceIo_CIL___Tmp11 >= 259) && (FlFdcDeviceIo_CIL___Tmp11 <= 259)) {
        KeWaitForSingleObject(FlFdcDeviceIo_doneEvent, Suspended, KernelMode, 0, 0);
        FlFdcDeviceIo_ntStatus = myStatus;
      }
      retres12 = FlFdcDeviceIo_ntStatus;
    }
    return (retres12);
  }
}
void FloppyProcessQueuedRequests(int FloppyProcessQueuedRequests_DisketteExtension ) 
{ 

  {

    return;
  }
}
void stub_driver_init(void) 
{ 

  {
    s = NP;
    pended = 0;
    compRegistered = 0;
    lowerDriverReturn = 0;
    setEventCalled = 0;
    customIrp = 0;

    return;
  }
}
extern int __VERIFIER_nondet_int() ;
extern int (_TRACER_abort)() ;
int main(void) 
{ int main_status ;
  int main_irp ;
  int main_pirp ;
  int main_pirp__IoStatus__Status ;
  int main_irp_choice ;
  int main_devobj ;
  int main_tmp_ndt_1 ;
  int retres8 ;
  int TRACER_returning ;

  {
    TRACER_returning = 0;
    safety = 0;
    FloppyThread = 0;
    KernelMode = 0;
    Suspended = 0;
    Executive = 0;
    DiskController = 0;
    FloppyDiskPeripheral = 0;
    FlConfigCallBack = 0;
    MaximumInterfaceType = 0;
    MOUNTDEV_MOUNTED_DEVICE_GUID = 0;
    myStatus = 0;
    s = 0;
    UNLOADED = 0;
    NP = 0;
    DC = 0;
    SKIP1 = 0;
    SKIP2 = 0;
    MPR1 = 0;
    MPR3 = 0;
    IPC = 0;
    pended = 0;
    compRegistered = 0;
    lowerDriverReturn = 0;
    setEventCalled = 0;
    customIrp = 0;
    main_status = 0;
    main_pirp = main_irp;
    _BLAST_init();
    if (main_status >= 0) {
      s = NP;
      customIrp = 0;
      setEventCalled = customIrp;
      lowerDriverReturn = setEventCalled;
      compRegistered = lowerDriverReturn;
      pended = compRegistered;
      main_pirp__IoStatus__Status = 0;
      myStatus = 0;
      if ((main_irp_choice >= 0) && (main_irp_choice <= 0)) {
        main_pirp__IoStatus__Status = -1073741637;
        myStatus = -1073741637;
      }
      stub_driver_init();
      if (main_status < 0) {
        retres8 = -1;
        TRACER_returning = 1;
      }
      else {
        main_tmp_ndt_1 = __VERIFIER_nondet_int();
        if ((main_tmp_ndt_1 >= 3) && (main_tmp_ndt_1 <= 3)) {
          main_status = FloppyPnp(main_devobj, main_pirp);
        } else {
          retres8 = -1;
          TRACER_returning = 1;
        }
      }
    }
    if (TRACER_returning <= 0) {
      if ((pended >= 1) && (pended <= 1)) {
        if ((s >= NP) && (s <= NP)) {
          s = NP;
        } else {
          if ((pended >= 1) && (pended <= 1)) {
            if ((s >= MPR3) && (s <= MPR3)) {
              s = MPR3;
            } else {
              if ((s > UNLOADED) || (s < UNLOADED)) {
                if ((main_status > -1) || (main_status < -1)) {
                  if ((s > SKIP2) || (s < SKIP2)) {
                    if ((s > IPC) || (s < IPC)) {
                      safety = safety + (s - DC);
                    }
                    if ((pended >= 1) && (pended <= 1)) {
                      if ((main_status > 259) || (main_status < 259)) {
                        main_status = 0;
                      }
                    } else {
                      if ((s > DC) || (s < DC)) {
                        safety = safety + (main_status - lowerDriverReturn);
                      }
                    }
                  } else {
                    if ((pended >= 1) && (pended <= 1)) {
                      if ((main_status > 259) || (main_status < 259)) {
                        main_status = 0;
                      }
                    } else {
                      if ((s > DC) || (s < DC)) {
                        safety = safety + (main_status - lowerDriverReturn);
                      }
                    }
                  }
                }
              }
            }
          } else {
            if ((s > UNLOADED) || (s < UNLOADED)) {
              if ((main_status > -1) || (main_status < -1)) {
                if ((s > SKIP2) || (s < SKIP2)) {
                  if ((s > IPC) || (s < IPC)) {
                    safety = safety + (s - DC);
                  }
                  if ((pended >= 1) && (pended <= 1)) {
                    if ((main_status > 259) || (main_status < 259)) {
                      main_status = 0;
                    }
                  } else {
                    if ((s > DC) || (s < DC)) {
                      safety = safety + (main_status - lowerDriverReturn);
                    }
                  }
                } else {
                  if ((pended >= 1) && (pended <= 1)) {
                    if ((main_status > 259) || (main_status < 259)) {
                      main_status = 0;
                    }
                  } else {
                    if ((s > DC) || (s < DC)) {
                      safety = safety + (main_status - lowerDriverReturn);
                    }
                  }
                }
              }
            }
          }
        }
      } else {
        if ((pended >= 1) && (pended <= 1)) {
          if ((s >= MPR3) && (s <= MPR3)) {
            s = MPR3;
          } else {
            if ((s > UNLOADED) || (s < UNLOADED)) {
              if ((main_status > -1) || (main_status < -1)) {
                if ((s > SKIP2) || (s < SKIP2)) {
                  if ((s > IPC) || (s < IPC)) {
                    safety = safety + (s - DC);
                  }
                  if ((pended >= 1) && (pended <= 1)) {
                    if ((main_status > 259) || (main_status < 259)) {
                      main_status = 0;
                    }
                  } else {
                    if ((s > DC) || (s < DC)) {
                      safety = safety + (main_status - lowerDriverReturn);
                    }
                  }
                } else {
                  if ((pended >= 1) && (pended <= 1)) {
                    if ((main_status > 259) || (main_status < 259)) {
                      main_status = 0;
                    }
                  } else {
                    if ((s > DC) || (s < DC)) {
                      safety = safety + (main_status - lowerDriverReturn);
                    }
                  }
                }
              }
            }
          }
        } else {
          if ((s > UNLOADED) || (s < UNLOADED)) {
            if ((main_status > -1) || (main_status < -1)) {
              if ((s > SKIP2) || (s < SKIP2)) {
                if ((s > IPC) || (s < IPC)) {
                  safety = safety + (s - DC);
                }
                if ((pended >= 1) && (pended <= 1)) {
                  if ((main_status > 259) || (main_status < 259)) {
                    main_status = 0;
                  }
                } else {
                  if ((s > DC) || (s < DC)) {
                    safety = safety + (main_status - lowerDriverReturn);
                  }
                }
              } else {
                if ((pended >= 1) && (pended <= 1)) {
                  if ((main_status > 259) || (main_status < 259)) {
                    main_status = 0;
                  }
                } else {
                  if ((s > DC) || (s < DC)) {
                    safety = safety + (main_status - lowerDriverReturn);
                  }
                }
              }
            }
          }
        }
      }
      main_status = 0;
      retres8 = main_status;
    }
    if (safety != 0) goto ERROR;
    return (retres8);
    ERROR:;
  }
}
int IoBuildDeviceIoControlRequest(int IoBuildDeviceIoControlRequest_IoControlCode , int IoBuildDeviceIoControlRequest_DeviceObject , int IoBuildDeviceIoControlRequest_InputBuffer , int IoBuildDeviceIoControlRequest_InputBufferLength , int IoBuildDeviceIoControlRequest_OutputBuffer , int IoBuildDeviceIoControlRequest_OutputBufferLength , int IoBuildDeviceIoControlRequest_InternalDeviceIoControl , int IoBuildDeviceIoControlRequest_Event , int IoBuildDeviceIoControlRequest_IoStatusBlock ) 
{ int IoBuildDeviceIoControlRequest_malloc ;
  int IoBuildDeviceIoControlRequest_tmp_ndt_2 ;
  int retres12 ;

  {
    customIrp = 1;
    IoBuildDeviceIoControlRequest_tmp_ndt_2 = __VERIFIER_nondet_int();
    if ((IoBuildDeviceIoControlRequest_tmp_ndt_2 >= 0) && (IoBuildDeviceIoControlRequest_tmp_ndt_2 <= 0)) {
      retres12 = IoBuildDeviceIoControlRequest_malloc;
    } else {
      retres12 = 0;
    }
    return (retres12);
  }
}
int IoDeleteSymbolicLink(int IoDeleteSymbolicLink_SymbolicLinkName ) 
{ int IoDeleteSymbolicLink_tmp_ndt_3 ;
  int retres3 ;

  {
    IoDeleteSymbolicLink_tmp_ndt_3 = __VERIFIER_nondet_int();
    if ((IoDeleteSymbolicLink_tmp_ndt_3 >= 0) && (IoDeleteSymbolicLink_tmp_ndt_3 <= 0)) {
      retres3 = 0;
    } else {
      retres3 = -1073741823;
    }
    return (retres3);
  }
}
int IoQueryDeviceDescription(int IoQueryDeviceDescription_BusType , int IoQueryDeviceDescription_BusNumber , int IoQueryDeviceDescription_ControllerType , int IoQueryDeviceDescription_ControllerNumber , int IoQueryDeviceDescription_PeripheralType , int IoQueryDeviceDescription_PeripheralNumber , int IoQueryDeviceDescription_CalloutRoutine , int IoQueryDeviceDescription_Context ) 
{ int IoQueryDeviceDescription_tmp_ndt_4 ;
  int retres10 ;

  {
    IoQueryDeviceDescription_tmp_ndt_4 = __VERIFIER_nondet_int();
    if ((IoQueryDeviceDescription_tmp_ndt_4 >= 0) && (IoQueryDeviceDescription_tmp_ndt_4 <= 0)) {
      retres10 = 0;
    } else {
      retres10 = -1073741823;
    }
    return (retres10);
  }
}
int IoRegisterDeviceInterface(int IoRegisterDeviceInterface_PhysicalDeviceObject , int IoRegisterDeviceInterface_InterfaceClassGuid , int IoRegisterDeviceInterface_ReferenceString , int IoRegisterDeviceInterface_SymbolicLinkName ) 
{ int IoRegisterDeviceInterface_tmp_ndt_5 ;
  int retres6 ;

  {
    IoRegisterDeviceInterface_tmp_ndt_5 = __VERIFIER_nondet_int();
    if ((IoRegisterDeviceInterface_tmp_ndt_5 >= 0) && (IoRegisterDeviceInterface_tmp_ndt_5 <= 0)) {
      retres6 = 0;
    } else {
      retres6 = -1073741808;
    }
    return (retres6);
  }
}
int IoSetDeviceInterfaceState(int IoSetDeviceInterfaceState_SymbolicLinkName , int IoSetDeviceInterfaceState_Enable ) 
{ int IoSetDeviceInterfaceState_tmp_ndt_6 ;
  int retres4 ;

  {
    IoSetDeviceInterfaceState_tmp_ndt_6 = __VERIFIER_nondet_int();
    if ((IoSetDeviceInterfaceState_tmp_ndt_6 >= 0) && (IoSetDeviceInterfaceState_tmp_ndt_6 <= 0)) {
      retres4 = 0;
    } else {
      retres4 = -1073741823;
    }
    return (retres4);
  }
}
void stubMoreProcessingRequired(void) 
{ 

  {
    safety = safety + (s - NP);
    s = MPR1;

    return;
  }
}
int IofCallDriver(int IofCallDriver_DeviceObject , int IofCallDriver_Irp ) 
{ int IofCallDriver_returnVal2 ;
  int IofCallDriver_compRetStatus1 ;
  int IofCallDriver_lcontext ;
  int IofCallDriver_CIL___Tmp7 ;
  int IofCallDriver_tmp_ndt_7 ;
  int IofCallDriver_tmp_ndt_8 ;

  {
    if ((compRegistered > 0) || (compRegistered < 0)) {
      IofCallDriver_compRetStatus1 = FloppyPnpComplete(IofCallDriver_DeviceObject, IofCallDriver_Irp, IofCallDriver_lcontext);
      IofCallDriver_CIL___Tmp7 = IofCallDriver_compRetStatus1;
      if ((IofCallDriver_CIL___Tmp7 >= -1073741802) && (IofCallDriver_CIL___Tmp7 <= -1073741802)) {
        stubMoreProcessingRequired();
      }
    }
    IofCallDriver_tmp_ndt_7 = __VERIFIER_nondet_int();
    if ((IofCallDriver_tmp_ndt_7 >= 0) && (IofCallDriver_tmp_ndt_7 <= 0)) {
      IofCallDriver_returnVal2 = 0;
    } else {
      IofCallDriver_tmp_ndt_8 = __VERIFIER_nondet_int();
      if ((IofCallDriver_tmp_ndt_8 >= 1) && (IofCallDriver_tmp_ndt_8 <= 1)) {
        IofCallDriver_returnVal2 = -1073741823;
      } else {
        IofCallDriver_returnVal2 = 259;
      }
    }
    if ((s >= NP) && (s <= NP)) {
      s = IPC;
      lowerDriverReturn = IofCallDriver_returnVal2;
    } else {
      if ((s >= MPR1) && (s <= MPR1)) {
        if ((IofCallDriver_returnVal2 >= 259) && (IofCallDriver_returnVal2 <= 259)) {
          s = MPR3;
          lowerDriverReturn = IofCallDriver_returnVal2;
        } else {
          s = NP;
          lowerDriverReturn = IofCallDriver_returnVal2;
        }
      } else {
        safety = safety + (s - SKIP1);
        s = SKIP2;
        lowerDriverReturn = IofCallDriver_returnVal2;
      }
    }
    return (IofCallDriver_returnVal2);
  }
}
void IofCompleteRequest(int IofCompleteRequest_Irp , int IofCompleteRequest_PriorityBoost ) 
{ 

  {
    safety = safety + (s - NP);
    s = DC;

    return;
  }
}
int KeSetEvent(int KeSetEvent_Event , int KeSetEvent_Increment , int KeSetEvent_Wait ) 
{ int KeSetEvent_l ;

  {
    setEventCalled = 1;
    return (KeSetEvent_l);
  }
}
int KeWaitForSingleObject(int KeWaitForSingleObject_Object , int KeWaitForSingleObject_WaitReason , int KeWaitForSingleObject_WaitMode , int KeWaitForSingleObject_Alertable , int KeWaitForSingleObject_Timeout ) 
{ int KeWaitForSingleObject_tmp_ndt_9 ;
  int retres7 ;

  {
    if ((s >= MPR3) && (s <= MPR3)) {
      if ((setEventCalled >= 1) && (setEventCalled <= 1)) {
        s = NP;
        setEventCalled = 0;
      } else {
        if ((customIrp >= 1) && (customIrp <= 1)) {
          s = NP;
          customIrp = 0;
        }
      }
    } else {
      if ((customIrp >= 1) && (customIrp <= 1)) {
        s = NP;
        customIrp = 0;
      }
    }
    KeWaitForSingleObject_tmp_ndt_9 = __VERIFIER_nondet_int();
    if ((KeWaitForSingleObject_tmp_ndt_9 >= 0) && (KeWaitForSingleObject_tmp_ndt_9 <= 0)) {
      retres7 = 0;
    } else {
      retres7 = -1073741823;
    }
    return (retres7);
  }
}
int ObReferenceObjectByHandle(int ObReferenceObjectByHandle_Handle , int ObReferenceObjectByHandle_DesiredAccess , int ObReferenceObjectByHandle_ObjectType , int ObReferenceObjectByHandle_AccessMode , int ObReferenceObjectByHandle_Object , int ObReferenceObjectByHandle_HandleInformation ) 
{ int ObReferenceObjectByHandle_tmp_ndt_10 ;
  int retres8 ;

  {
    ObReferenceObjectByHandle_tmp_ndt_10 = __VERIFIER_nondet_int();
    if ((ObReferenceObjectByHandle_tmp_ndt_10 >= 0) && (ObReferenceObjectByHandle_tmp_ndt_10 <= 0)) {
      retres8 = 0;
    } else {
      retres8 = -1073741823;
    }
    return (retres8);
  }
}
int PsCreateSystemThread(int PsCreateSystemThread_ThreadHandle , int PsCreateSystemThread_DesiredAccess , int PsCreateSystemThread_ObjectAttributes , int PsCreateSystemThread_ProcessHandle , int PsCreateSystemThread_ClientId , int PsCreateSystemThread_StartRoutine , int PsCreateSystemThread_StartContext ) 
{ int PsCreateSystemThread_tmp_ndt_11 ;
  int retres9 ;

  {
    PsCreateSystemThread_tmp_ndt_11 = __VERIFIER_nondet_int();
    if ((PsCreateSystemThread_tmp_ndt_11 >= 0) && (PsCreateSystemThread_tmp_ndt_11 <= 0)) {
      retres9 = 0;
    } else {
      retres9 = -1073741823;
    }
    return (retres9);
  }
}
int ZwClose(int ZwClose_Handle ) 
{ int ZwClose_tmp_ndt_12 ;
  int retres3 ;

  {
    ZwClose_tmp_ndt_12 = __VERIFIER_nondet_int();
    if ((ZwClose_tmp_ndt_12 >= 0) && (ZwClose_tmp_ndt_12 <= 0)) {
      retres3 = 0;
    } else {
      retres3 = -1073741823;
    }
    return (retres3);
  }
}
int FloppyCreateClose(int FloppyCreateClose_DeviceObject , int FloppyCreateClose_Irp ) 
{ int FloppyCreateClose_Irp__IoStatus__Status ;
  int FloppyCreateClose_Irp__IoStatus__Information ;
  int retres5 ;

  {
    myStatus = 0;
    FloppyCreateClose_Irp__IoStatus__Status = 0;
    FloppyCreateClose_Irp__IoStatus__Information = 1;
    IofCompleteRequest(FloppyCreateClose_Irp, 0);
    retres5 = 0;
    return (retres5);
  }
}
