/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern int ( /* missing proto */  __VERIFIER_nondet_int)() ;
int ssl3_connect(int initial_state ) 
{ int s__info_callback ;
  int s__in_handshake ;
  int s__state ;
  int s__new_session ;
  int s__server ;
  int s__version ;
  int s__type ;
  int s__init_num ;
  int s__bbio ;
  int s__wbio ;
  int s__hit ;
  int s__rwstate ;
  int s__init_buf___0 ;
  int s__debug ;
  int s__shutdown ;
  int s__ctx__info_callback ;
  int s__ctx__stats__sess_connect_renegotiate ;
  int s__ctx__stats__sess_connect ;
  int s__ctx__stats__sess_hit ;
  int s__ctx__stats__sess_connect_good ;
  int s__s3__change_cipher_spec ;
  int s__s3__flags ;
  int s__s3__delay_buf_pop_ret ;
  int s__s3__tmp__cert_req ;
  int s__s3__tmp__new_compression ;
  int s__s3__tmp__reuse_message ;
  int s__s3__tmp__new_cipher ;
  int s__s3__tmp__new_cipher__algorithms ;
  int s__s3__tmp__next_state___0 ;
  int s__s3__tmp__new_compression__id ;
  int s__session__cipher ;
  int s__session__compress_meth ;
  int buf ;
  unsigned long tmp ;
  unsigned long l ;
  int num1 ;
  int cb ;
  int ret ;
  int new_state ;
  int state ;
  int skip ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int blastFlag ;
  int CIL___tmp55 ;
  void *CIL___tmp56 ;
  unsigned long CIL___tmp57 ;
  unsigned long CIL___tmp58 ;
  void *CIL___tmp59 ;
  unsigned long CIL___tmp60 ;
  unsigned long CIL___tmp61 ;
  unsigned long CIL___tmp62 ;
  unsigned long CIL___tmp63 ;
  unsigned long CIL___tmp64 ;
  long CIL___tmp65 ;
  long CIL___tmp66 ;
  long CIL___tmp67 ;
  long CIL___tmp68 ;
  long CIL___tmp69 ;
  long CIL___tmp70 ;
  long CIL___tmp71 ;
  long CIL___tmp72 ;
  long CIL___tmp73 ;
  long CIL___tmp74 ;
  int CIL___tmp ;

  {
  s__state = initial_state;
  blastFlag = 0;
  CIL___tmp = __VERIFIER_nondet_int();
  tmp = (unsigned long )CIL___tmp;
  cb = 0;
  ret = -1;
  skip = 0;
  tmp___0 = 0;
  if (s__info_callback != 0) {
    cb = s__info_callback;
  } else {
    if (s__ctx__info_callback != 0) {
      cb = s__ctx__info_callback;
    }
  }
  s__in_handshake = s__in_handshake + 1;
  if (tmp___1 + 12288) {
    if (tmp___2 + 16384) {

    }
  }
  while (1) {
    while_0_continue: 
    state = s__state;
    switch(s__state) {
        case 12292: 
        s__new_session = 1;
        s__state = 4096;
        s__ctx__stats__sess_connect_renegotiate = s__ctx__stats__sess_connect_renegotiate + 1;
        case 16384: ;
        case 4096: ;
        case 20480: ;
        case 4099: 
        s__server = 0;
        if (cb != 0) {

        }
        CIL___tmp55 = s__version + 65280;
        if (CIL___tmp55 != 768) {
          ret = -1;
          goto end;
        }
        s__type = 4096;
        CIL___tmp56 = (void *)0;
        CIL___tmp57 = (unsigned long )CIL___tmp56;
        CIL___tmp58 = (unsigned long )s__init_buf___0;
        if (CIL___tmp58 == CIL___tmp57) {
          buf = __VERIFIER_nondet_int();
          CIL___tmp59 = (void *)0;
          CIL___tmp60 = (unsigned long )CIL___tmp59;
          CIL___tmp61 = (unsigned long )buf;
          if (CIL___tmp61 == CIL___tmp60) {
            ret = -1;
            goto end;
          }
          if (! tmp___3) {
            ret = -1;
            goto end;
          }
          s__init_buf___0 = buf;
        }
        if (! tmp___4) {
          ret = -1;
          goto end;
        }
        if (! tmp___5) {
          ret = -1;
          goto end;
        }
        s__state = 4368;
        s__ctx__stats__sess_connect = s__ctx__stats__sess_connect + 1;
        s__init_num = 0;
        break;
        case 4368: ;
        case 4369: 
        s__shutdown = 0;
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 0) {
          blastFlag = 1;
        }
        if (ret <= 0) {
          goto end;
        }
        s__state = 4384;
        s__init_num = 0;
        CIL___tmp62 = (unsigned long )s__wbio;
        CIL___tmp63 = (unsigned long )s__bbio;
        if (CIL___tmp63 != CIL___tmp62) {

        }
        break;
        case 4384: ;
        case 4385: 
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 1) {
          blastFlag = 2;
        } else {
          if (blastFlag == 4) {
            blastFlag = 5;
          }
        }
        if (ret <= 0) {
          goto end;
        }
        if (s__hit) {
          s__state = 4560;
        } else {
          s__state = 4400;
        }
        s__init_num = 0;
        break;
        case 4400: ;
        case 4401: 
        CIL___tmp64 = (unsigned long )s__s3__tmp__new_cipher__algorithms;
        if (CIL___tmp64 + 256UL) {
          skip = 1;
        } else {
          ret = __VERIFIER_nondet_int();
          if (blastFlag == 2) {
            blastFlag = 3;
          }
          if (ret <= 0) {
            goto end;
          }
        }
        s__state = 4416;
        s__init_num = 0;
        break;
        case 4416: ;
        case 4417: 
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 3) {
          blastFlag = 4;
        }
        if (ret <= 0) {
          goto end;
        }
        s__state = 4432;
        s__init_num = 0;
        if (! tmp___6) {
          ret = -1;
          goto end;
        }
        break;
        case 4432: ;
        case 4433: 
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 5) {
          _TRACER_abort(1);
        }
        if (ret <= 0) {
          goto end;
        }
        s__state = 4448;
        s__init_num = 0;
        break;
        case 4448: ;
        case 4449: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        if (s__s3__tmp__cert_req) {
          s__state = 4464;
        } else {
          s__state = 4480;
        }
        s__init_num = 0;
        break;
        case 4464: ;
        case 4465: ;
        case 4466: ;
        case 4467: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__state = 4480;
        s__init_num = 0;
        break;
        case 4480: ;
        case 4481: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        l = (unsigned long )s__s3__tmp__new_cipher__algorithms;
        if (s__s3__tmp__cert_req == 1) {
          s__state = 4496;
        } else {
          s__state = 4512;
          s__s3__change_cipher_spec = 0;
        }
        s__init_num = 0;
        break;
        case 4496: ;
        case 4497: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__state = 4512;
        s__init_num = 0;
        s__s3__change_cipher_spec = 0;
        break;
        case 4512: ;
        case 4513: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__state = 4528;
        s__init_num = 0;
        s__session__cipher = s__s3__tmp__new_cipher;
        if (s__s3__tmp__new_compression == 0) {
          s__session__compress_meth = 0;
        } else {
          s__session__compress_meth = s__s3__tmp__new_compression__id;
        }
        if (! tmp___7) {
          ret = -1;
          goto end;
        }
        if (! tmp___8) {
          ret = -1;
          goto end;
        }
        break;
        case 4528: ;
        case 4529: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__state = 4352;
        CIL___tmp65 = (long )s__s3__flags;
        CIL___tmp66 = CIL___tmp65 - 5L;
        s__s3__flags = (int )CIL___tmp66;
        if (s__hit) {
          s__s3__tmp__next_state___0 = 3;
          CIL___tmp67 = (long )s__s3__flags;
          if (CIL___tmp67 + 2L) {
            s__state = 3;
            CIL___tmp68 = (long )s__s3__flags;
            CIL___tmp69 = CIL___tmp68 * 4L;
            s__s3__flags = (int )CIL___tmp69;
            s__s3__delay_buf_pop_ret = 0;
          }
        } else {
          s__s3__tmp__next_state___0 = 4560;
        }
        s__init_num = 0;
        break;
        case 4560: ;
        case 4561: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        if (s__hit) {
          s__state = 4512;
        } else {
          s__state = 3;
        }
        s__init_num = 0;
        break;
        case 4352: 
        CIL___tmp70 = (long )num1;
        if (CIL___tmp70 > 0L) {
          s__rwstate = 2;
          CIL___tmp71 = (long )tmp___9;
          num1 = (int )CIL___tmp71;
          CIL___tmp72 = (long )num1;
          if (CIL___tmp72 <= 0L) {
            ret = -1;
            goto end;
          }
          s__rwstate = 1;
        }
        s__state = s__s3__tmp__next_state___0;
        break;
        case 3: 
        if (s__init_buf___0 != 0) {
          s__init_buf___0 = 0;
        }
        CIL___tmp73 = (long )s__s3__flags;
        CIL___tmp74 = CIL___tmp73 + 4L;
        if (! CIL___tmp74) {

        }
        s__init_num = 0;
        s__new_session = 0;
        if (s__hit) {
          s__ctx__stats__sess_hit = s__ctx__stats__sess_hit + 1;
        }
        ret = 1;
        s__ctx__stats__sess_connect_good = s__ctx__stats__sess_connect_good + 1;
        if (cb != 0) {

        }
        goto end;
        default: 
        ret = -1;
        goto end;
    }
    if (! s__s3__tmp__reuse_message) {
      if (! skip) {
        if (s__debug) {
          ret = __VERIFIER_nondet_int();
          if (ret <= 0) {
            goto end;
          }
        }
        if (cb != 0) {
          if (s__state != state) {
            new_state = s__state;
            s__state = state;
            s__state = new_state;
          }
        }
      }
    }
    skip = 0;
  }
  while_0_break: ;
  end: 
  s__in_handshake = s__in_handshake - 1;
  if (cb != 0) {

  }
  return (ret);
  ERROR: 
  return (-1);
}
}
int main(void) 
{ int s ;

  {
  s = 12292;
  ssl3_connect(s);
  return (0);
}
}
