/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern int ( /* missing proto */  __VERIFIER_nondet_int)() ;
int ssl3_accept(int initial_state ) 
{ int s__info_callback ;
  int s__in_handshake ;
  int s__state ;
  int s__new_session ;
  int s__server ;
  int s__version ;
  int s__type ;
  int s__init_num ;
  int s__hit ;
  int s__rwstate ;
  int s__init_buf___0 ;
  int s__debug ;
  int s__shutdown ;
  int s__cert ;
  int s__options ;
  int s__verify_mode ;
  int s__session__peer ;
  int s__cert__pkeys__AT0__privatekey ;
  int s__ctx__info_callback ;
  int s__ctx__stats__sess_accept_renegotiate ;
  int s__ctx__stats__sess_accept ;
  int s__ctx__stats__sess_accept_good ;
  int s__s3__tmp__cert_request ;
  int s__s3__tmp__reuse_message ;
  int s__s3__tmp__use_rsa_tmp ;
  int s__s3__tmp__new_cipher ;
  int s__s3__tmp__new_cipher__algorithms ;
  int s__s3__tmp__next_state___0 ;
  int s__s3__tmp__new_cipher__algo_strength ;
  int s__session__cipher ;
  int buf ;
  unsigned long l ;
  unsigned long Time ;
  unsigned long tmp ;
  int cb ;
  long num1 ;
  int ret ;
  int new_state ;
  int state ;
  int skip ;
  int got_new_session ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  long tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int blastFlag ;
  int CIL___tmp55 ;
  unsigned long CIL___tmp56 ;
  unsigned long CIL___tmp57 ;
  unsigned long CIL___tmp58 ;
  unsigned long CIL___tmp59 ;
  int CIL___tmp60 ;
  unsigned long CIL___tmp61 ;
  int CIL___tmp ;

  {
  s__state = initial_state;
  blastFlag = 0;
  CIL___tmp = __VERIFIER_nondet_int();
  tmp = (unsigned long )CIL___tmp;
  Time = tmp;
  cb = 0;
  ret = -1;
  skip = 0;
  got_new_session = 0;
  if (s__info_callback != 0) {
    cb = s__info_callback;
  } else {
    if (s__ctx__info_callback != 0) {
      cb = s__ctx__info_callback;
    }
  }
  s__in_handshake = s__in_handshake + 1;
  if (tmp___1 + 12288) {
    if (tmp___2 + 16384) {

    }
  }
  if (s__cert == 0) {
    return (-1);
  }
  while (1) {
    while_0_continue: 
    state = s__state;
    switch(s__state) {
        case 12292: 
        s__new_session = 1;
        case 16384: ;
        case 8192: ;
        case 24576: ;
        case 8195: 
        s__server = 1;
        if (cb != 0) {

        }
        CIL___tmp55 = s__version * 8;
        if (CIL___tmp55 != 3) {
          return (-1);
        }
        s__type = 8192;
        if (s__init_buf___0 == 0) {
          buf = __VERIFIER_nondet_int();
          if (buf == 0) {
            ret = -1;
            goto end;
          }
          if (! tmp___3) {
            ret = -1;
            goto end;
          }
          s__init_buf___0 = buf;
        }
        if (! tmp___4) {
          ret = -1;
          goto end;
        }
        s__init_num = 0;
        if (s__state != 12292) {
          if (! tmp___5) {
            ret = -1;
            goto end;
          }
          s__state = 8464;
          s__ctx__stats__sess_accept = s__ctx__stats__sess_accept + 1;
        } else {
          s__ctx__stats__sess_accept_renegotiate = s__ctx__stats__sess_accept_renegotiate + 1;
          s__state = 8480;
        }
        break;
        case 8480: ;
        case 8481: 
        s__shutdown = 0;
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__s3__tmp__next_state___0 = 8482;
        s__state = 8448;
        s__init_num = 0;
        break;
        case 8482: 
        s__state = 3;
        break;
        case 8464: ;
        case 8465: ;
        case 8466: 
        s__shutdown = 0;
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 0) {
          blastFlag = 1;
        }
        if (ret <= 0) {
          goto end;
        }
        got_new_session = 1;
        s__state = 8496;
        s__init_num = 0;
        break;
        case 8496: ;
        case 8497: 
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 1) {
          blastFlag = 2;
        } else {
          if (blastFlag == 3) {
            blastFlag = 4;
          }
        }
        if (ret <= 0) {
          goto end;
        }
        if (s__hit) {
          s__state = 8656;
        } else {
          s__state = 8512;
        }
        s__init_num = 0;
        break;
        case 8512: ;
        case 8513: 
        CIL___tmp56 = (unsigned long )s__s3__tmp__new_cipher__algorithms;
        if (CIL___tmp56 + 256UL) {
          skip = 1;
        } else {
          ret = __VERIFIER_nondet_int();
          if (ret <= 0) {
            goto end;
          }
        }
        s__state = 8528;
        s__init_num = 0;
        break;
        case 8528: ;
        case 8529: 
        l = (unsigned long )s__s3__tmp__new_cipher__algorithms;
        CIL___tmp57 = (unsigned long )s__options;
        if (CIL___tmp57 + 2097152UL) {
          s__s3__tmp__use_rsa_tmp = 1;
        } else {
          s__s3__tmp__use_rsa_tmp = 0;
        }
        if (s__s3__tmp__use_rsa_tmp) {
          goto _L___0;
        } else {
          if (l + 30UL) {
            goto _L___0;
          } else {
            if (l + 1UL) {
              if (s__cert__pkeys__AT0__privatekey == 0) {
                goto _L___0;
              } else {
                CIL___tmp58 = (unsigned long )s__s3__tmp__new_cipher__algo_strength;
                if (CIL___tmp58 + 2UL) {
                  CIL___tmp59 = (unsigned long )s__s3__tmp__new_cipher__algo_strength;
                  if (CIL___tmp59 + 4UL) {
                    tmp___7 = 512;
                  } else {
                    tmp___7 = 1024;
                  }
                  CIL___tmp60 = tmp___6 * 8;
                  if (CIL___tmp60 > tmp___7) {
                    _L___0: 
                    ret = __VERIFIER_nondet_int();
                    if (ret <= 0) {
                      goto end;
                    }
                  } else {
                    skip = 1;
                  }
                } else {
                  skip = 1;
                }
              }
            } else {
              skip = 1;
            }
          }
        }
        s__state = 8544;
        s__init_num = 0;
        break;
        case 8544: ;
        case 8545: ;
        if (s__verify_mode + 1) {
          if (s__session__peer != 0) {
            if (s__verify_mode + 4) {
              skip = 1;
              s__s3__tmp__cert_request = 0;
              s__state = 8560;
            } else {
              goto _L___2;
            }
          } else {
            _L___2: 
            CIL___tmp61 = (unsigned long )s__s3__tmp__new_cipher__algorithms;
            if (CIL___tmp61 + 256UL) {
              if (s__verify_mode + 2) {
                goto _L___1;
              } else {
                skip = 1;
                s__s3__tmp__cert_request = 0;
                s__state = 8560;
              }
            } else {
              _L___1: 
              s__s3__tmp__cert_request = 1;
              ret = __VERIFIER_nondet_int();
              if (ret <= 0) {
                goto end;
              }
              s__state = 8448;
              s__s3__tmp__next_state___0 = 8576;
              s__init_num = 0;
            }
          }
        } else {
          skip = 1;
          s__s3__tmp__cert_request = 0;
          s__state = 8560;
        }
        break;
        case 8560: ;
        case 8561: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__s3__tmp__next_state___0 = 8576;
        s__state = 8448;
        s__init_num = 0;
        break;
        case 8448: 
        if (num1 > 0L) {
          s__rwstate = 2;
          num1 = tmp___8;
          if (num1 <= 0L) {
            ret = -1;
            goto end;
          }
          s__rwstate = 1;
        }
        s__state = s__s3__tmp__next_state___0;
        break;
        case 8576: ;
        case 8577: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        if (ret == 2) {
          s__state = 8466;
        } else {
          ret = __VERIFIER_nondet_int();
          if (ret <= 0) {
            goto end;
          }
          s__init_num = 0;
          s__state = 8592;
        }
        break;
        case 8592: ;
        case 8593: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__state = 8608;
        s__init_num = 0;
        break;
        case 8608: ;
        case 8609: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        s__state = 8640;
        s__init_num = 0;
        break;
        case 8640: ;
        case 8641: 
        ret = __VERIFIER_nondet_int();
        if (ret <= 0) {
          goto end;
        }
        if (s__hit) {
          s__state = 3;
        } else {
          s__state = 8656;
        }
        s__init_num = 0;
        break;
        case 8656: ;
        case 8657: 
        s__session__cipher = s__s3__tmp__new_cipher;
        if (! tmp___9) {
          ret = -1;
          goto end;
        }
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 2) {
          blastFlag = 3;
        }
        if (ret <= 0) {
          goto end;
        }
        s__state = 8672;
        s__init_num = 0;
        if (! tmp___10) {
          ret = -1;
          goto end;
        }
        break;
        case 8672: ;
        case 8673: 
        ret = __VERIFIER_nondet_int();
        if (blastFlag == 4) {
          _TRACER_abort(1);
        }
        if (ret <= 0) {
          goto end;
        }
        s__state = 8448;
        if (s__hit) {
          s__s3__tmp__next_state___0 = 8640;
        } else {
          s__s3__tmp__next_state___0 = 3;
        }
        s__init_num = 0;
        break;
        case 3: 
        s__init_buf___0 = 0;
        s__init_num = 0;
        if (got_new_session) {
          s__new_session = 0;
          s__ctx__stats__sess_accept_good = s__ctx__stats__sess_accept_good + 1;
          if (cb != 0) {

          }
        }
        ret = 1;
        goto end;
        default: 
        ret = -1;
        goto end;
      }

    if (! s__s3__tmp__reuse_message) {
      if (! skip) {
        if (s__debug) {
          ret = __VERIFIER_nondet_int();
          if (ret <= 0) {
            goto end;
          }
        }
        if (cb != 0) {
          if (s__state != state) {
            new_state = s__state;
            s__state = state;
            s__state = new_state;
          }
        }
      }
    }
    skip = 0;
  }
  while_0_break: ;
  end: 
  s__in_handshake = s__in_handshake - 1;
  if (cb != 0) {

  }
  return (ret);
  ERROR: 
  return (-1);
}
}
int main(void) 
{ int s ;
  int tmp ;

  {
  s = 8464;
  tmp = ssl3_accept(s);
  return (tmp);
}
}
