##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2011                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

##########################################################################
#                                                                        #
# Define variables from configure.                                       #
# These variables may be redefined later.                                #
#                                                                        #
##########################################################################

#######################
# Working directories #
#######################

FRAMAC_TOP_SRCDIR 	?= /home/vijay/new-new-work/TRACER/trunk/lib/frama-c-Nitrogen-20111001

######################
# Installation paths #
######################

DESTDIR 	?=
prefix		?=/usr/local
exec_prefix	?=${prefix}
datarootdir     ?=${prefix}/share
datadir         ?=${datarootdir}
BINDIR		?="$(DESTDIR)${exec_prefix}/bin"
LIBDIR		?="$(DESTDIR)${exec_prefix}/lib"
DATADIR		?="$(DESTDIR)${prefix}/share"
MANDIR		?="$(DESTDIR)${datarootdir}/man"

FRAMAC_LIBDIR	?=$(LIBDIR)/frama-c
FRAMAC_PLUGINDIR ?=$(FRAMAC_LIBDIR)/plugins
FRAMAC_DATADIR 	?=$(DATADIR)/frama-c
EMACS_DATADIR	?=$(DATADIR)/emacs/site-lisp

###############
# Ocaml stuff #
###############

# compilers and others executables
OCAMLC  	?=ocamlc
OCAMLOPT	?=ocamlopt
OCAMLDEP	?=ocamldep -slash
OCAMLLEX	?=ocamllex
OCAMLYACC	?=ocamlyacc
OCAMLMKTOP	?=ocamlmktop
OCAMLDOC	?=ocamldoc
OCAMLCP		?=ocamlcp

# others ocaml stuffs

# either -annot or -dtypes
OCAML_ANNOT_OPTION ?=-annot
# ocaml stdlib path
OCAMLLIB	?=/usr/lib/ocaml
# either opt or byte
OCAMLBEST	?=opt
OCAMLVERSION 	?=3.11.2
NATIVE_DYNLINK  ?=yes
USABLE_NATIVE_DYNLINK ?=yes
OCAMLWIN32	?=no

#############
# Libraries #
#############

# ocamlgraph
OCAMLGRAPH_INCLUDE?= # ocamlgraph compilation directive
OCAMLGRAPH_LOCAL  ?=ocamlgraph
OCAMLGRAPH_HOME   ?=

# lablgtk
HAS_LABLGTK	?=yes
HAS_LABLGTK_CUSTOM_MODEL ?=yes

# lablgtksourceview
HAS_GTKSOURCEVIEW ?=no
HAS_LEGACY_GTKSOURCEVIEW ?=

# lablgnomecanvas
HAS_GNOMECANVAS	?=yes

# lablglade
HAS_LABLGLADECC	?=@HAS_LABLGLADECC@
LABLGLADECC	?=@LABLGLADECC@ -hide-default

##########################
# Miscellaneous commands #
##########################

OTAGS		?=
DOT		?=dot
HAS_DOT		?=yes

HEADACHE 	?= headache -c $(FRAMAC_SRC)/headers/headache_config.txt

###########################
# Miscellaneous variables #
###########################

VERBOSEMAKE	?=no
LOCAL_MACHDEP	?=no
EXE		?=

# Required by Cil
UNDERSCORE_NAME ?=
HAVE_BUILTIN_VA_LIST ?=
THREAD_IS_KEYWORD ?=

##########################
# Variables for plug-ins #
##########################

EXTERNAL_PLUGINS ?= src/aorai src/report src/security_slicing src/wp 

# Integrated plugins
ENABLE_FROM_ANALYSIS              ?=yes
ENABLE_GUI	                  ?=no
ENABLE_IMPACT	                  ?=partial
ENABLE_INOUT	                  ?=yes
ENABLE_METRICS	                  ?=partial
ENABLE_OCCURRENCE                 ?=partial
ENABLE_PDG	                  ?=yes
ENABLE_POSTDOMINATORS             ?=yes
ENABLE_REPORT                     ?=yes
ENABLE_RTE_ANNOTATION             ?=yes
ENABLE_SCOPE	                  ?=partial
ENABLE_SEMANTIC_CALLGRAPH         ?=yes
ENABLE_SEMANTIC_CONSTANT_FOLDING  ?=yes
ENABLE_SLICING	                  ?=partial
ENABLE_SPARECODE                  ?=yes
ENABLE_SYNTACTIC_CALLGRAPH        ?=partial
ENABLE_USERS	                  ?=yes
ENABLE_VALUE_ANALYSIS             ?=partial
