/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */
#include <crest.h>
int s  ;
int UNLOADED  ;
int NP  ;
int DC  ;
int SKIP1  ;
int SKIP2  ;
int MPR1  ;
int MPR3  ;
int IPC  ;
int pended  ;
int compFptr  ;
int compRegistered  ;
int lowerDriverReturn  ;
int setEventCalled  ;
int customIrp  ;
int myStatus  ;
int routine  ;
int pirp  ;
int Executive  ;
int KernelMode  ;
void _TRACER_assume(int x) { }
void errorFn(int i ) 
{ 

  {
  exit(1);
  _TRACER_assume(0);
}
}
void _BLAST_init(void) 
{ 

  {
  UNLOADED = 0;
  NP = 1;
  DC = 2;
  SKIP1 = 3;
  SKIP2 = 4;
  MPR1 = 5;
  MPR3 = 6;
  IPC = 7;
  s = UNLOADED;
  pended = 0;
  compFptr = 0;
  compRegistered = 0;
  lowerDriverReturn = 0;
  setEventCalled = 0;
  customIrp = 0;
  return;
}
}
void DiskPerfSyncFilterWithTarget(int FilterDevice , int TargetDevice ) 
{ 

  {
  return;
}
}
int DiskPerfStartDevice(int DeviceObject , int Irp ) ;
int DiskPerfRemoveDevice(int DeviceObject , int Irp ) ;
int DiskPerfSendToNextDriver(int DeviceObject , int Irp ) ;
int DiskPerfDispatchPnp(int DeviceObject , int Irp ) 
{ int Irp__Tail__Overlay__CurrentStackLocation ;
  int irpSp__MinorFunction ;
  int irpSp ;
  int status ;
  int tmp ;

  {
      CREST_int(tmp);
      CREST_int(status);
      CREST_int(irpSp);
      CREST_int(irpSp__MinorFunction);
      CREST_int(Irp__Tail__Overlay__CurrentStackLocation);
  irpSp = Irp__Tail__Overlay__CurrentStackLocation;
  if ((irpSp__MinorFunction >= 0) && (irpSp__MinorFunction <= 0)) {
    goto myswitch_0_0;
  } else {
    if ((irpSp__MinorFunction >= 2) && (irpSp__MinorFunction <= 2)) {
      goto myswitch_0_2;
    } else {
      goto myswitch_0_default;
      if (0) {
        myswitch_0_0: 
        status = DiskPerfStartDevice(DeviceObject, Irp);
        goto myswitch_0_break;
        myswitch_0_2: 
        status = DiskPerfRemoveDevice(DeviceObject, Irp);
        goto myswitch_0_break;
        myswitch_0_default: 
        tmp = DiskPerfSendToNextDriver(DeviceObject, Irp);
        return (tmp);
      } else {
        myswitch_0_break: ;
      }
    }
  }
  return (status);
}
}
int KeSetEvent(int Event , int Increment , int Wait ) ;
int DiskPerfIrpCompletion(int DeviceObject , int Irp , int Context ) 
{ int Event ;

  {
      CREST_int(Event);
  Event = Context;
  KeSetEvent(Event, 0, 0);
  return (-1073741802);
}
}
int DiskPerfForwardIrpSynchronous(int DeviceObject , int Irp ) ;
int DiskPerfRegisterDevice(int DeviceObject ) ;
void IofCompleteRequest(int Irp , int PriorityBoost ) ;
int DiskPerfStartDevice(int DeviceObject , int Irp ) 
{ int DeviceObject__DeviceExtension ;
  int deviceExtension__TargetDeviceObject ;
  int Irp__IoStatus__Status ;
  int deviceExtension ;
  int status ;

  {
      CREST_int(status);
      CREST_int(deviceExtension);
      CREST_int(Irp__IoStatus__Status);
      CREST_int(deviceExtension__TargetDeviceObject);
      CREST_int(DeviceObject__DeviceExtension);
  deviceExtension = DeviceObject__DeviceExtension;
  status = DiskPerfForwardIrpSynchronous(DeviceObject, Irp);
  DiskPerfSyncFilterWithTarget(DeviceObject, deviceExtension__TargetDeviceObject);
  DiskPerfRegisterDevice(DeviceObject);
  Irp__IoStatus__Status = status;
  myStatus = status;
  IofCompleteRequest(Irp, 0);
  return (status);
}
}
int DiskPerfRemoveDevice(int DeviceObject , int Irp ) 
{ int DeviceObject__DeviceExtension ;
  int deviceExtension__WmilibContext ;
  int Irp__IoStatus__Status ;
  int status ;
  int deviceExtension ;
  int wmilibContext ;

  {
      CREST_int(wmilibContext);
      CREST_int(deviceExtension);
      CREST_int(status);
      CREST_int(Irp__IoStatus__Status);
      CREST_int(deviceExtension__WmilibContext);
      CREST_int(DeviceObject__DeviceExtension);
  deviceExtension = DeviceObject__DeviceExtension;
  wmilibContext = deviceExtension__WmilibContext;
  status = DiskPerfForwardIrpSynchronous(DeviceObject, Irp);
  Irp__IoStatus__Status = status;
  myStatus = status;
  IofCompleteRequest(Irp, 0);
  return (status);
}
}
int IofCallDriver(int DeviceObject , int Irp ) ;
int DiskPerfSendToNextDriver(int DeviceObject , int Irp ) 
{ int Irp__CurrentLocation ;
  int Irp__Tail__Overlay__CurrentStackLocation ;
  int DeviceObject__DeviceExtension ;
  int deviceExtension__TargetDeviceObject ;
  int deviceExtension ;
  int tmp ;

  {
      CREST_int(tmp);
      CREST_int(deviceExtension);
      CREST_int(deviceExtension__TargetDeviceObject);
      CREST_int(DeviceObject__DeviceExtension);
      CREST_int(Irp__Tail__Overlay__CurrentStackLocation);
      CREST_int(Irp__CurrentLocation);
  if ((s >= NP) && (s <= NP)) {
    s = SKIP1;
  } else {
    errorFn(1);
  }
  Irp__CurrentLocation = Irp__CurrentLocation + 1;
  Irp__Tail__Overlay__CurrentStackLocation = Irp__Tail__Overlay__CurrentStackLocation + 1;
  deviceExtension = DeviceObject__DeviceExtension;
  tmp = IofCallDriver(deviceExtension__TargetDeviceObject, Irp);
  return (tmp);
}
}
int PoCallDriver(int DeviceObject , int Irp ) ;
int DiskPerfDispatchPower(int DeviceObject , int Irp ) 
{ int Irp__CurrentLocation ;
  int Irp__Tail__Overlay__CurrentStackLocation ;
  int DeviceObject__DeviceExtension ;
  int deviceExtension__TargetDeviceObject ;
  int deviceExtension ;
  int tmp ;

  {
      CREST_int(tmp);
      CREST_int(deviceExtension);
      CREST_int(deviceExtension__TargetDeviceObject);
      CREST_int(DeviceObject__DeviceExtension);
      CREST_int(Irp__Tail__Overlay__CurrentStackLocation);
      CREST_int(Irp__CurrentLocation);
  if ((s >= NP) && (s <= NP)) {
    s = SKIP1;
  } else {
    errorFn(1);
  }
  Irp__CurrentLocation = Irp__CurrentLocation + 1;
  Irp__Tail__Overlay__CurrentStackLocation = Irp__Tail__Overlay__CurrentStackLocation + 1;
  deviceExtension = DeviceObject__DeviceExtension;
  tmp = PoCallDriver(deviceExtension__TargetDeviceObject, Irp);
  return (tmp);
}
}
int KeWaitForSingleObject(int Object , int WaitReason , int WaitMode , int Alertable , int Timeout ) ;
int DiskPerfForwardIrpSynchronous(int DeviceObject , int Irp ) 
{ int Irp__Tail__Overlay__CurrentStackLocation ;
  int DeviceObject__DeviceExtension ;
  int deviceExtension__TargetDeviceObject ;
  int deviceExtension ;
  int event ;
  int status ;
  int nextIrpSp__Control ;
  int irpSp ;
  int nextIrpSp ;
  int irpSp__Context ;
  int irpSp__Control ;
  int irpSp___0 ;
  int CIL___Tmp15 ;

  {
      CREST_int(CIL___Tmp15);
      CREST_int(irpSp___0);
      CREST_int(irpSp__Control);
      CREST_int(irpSp__Context);
      CREST_int(nextIrpSp);
      CREST_int(irpSp);
      CREST_int(nextIrpSp__Control);
      CREST_int(status);
      CREST_int(event);
      CREST_int(deviceExtension);
      CREST_int(deviceExtension__TargetDeviceObject);
      CREST_int(DeviceObject__DeviceExtension);
      CREST_int(Irp__Tail__Overlay__CurrentStackLocation);
  deviceExtension = DeviceObject__DeviceExtension;
  irpSp = Irp__Tail__Overlay__CurrentStackLocation;
  nextIrpSp = Irp__Tail__Overlay__CurrentStackLocation - 1;
  nextIrpSp__Control = 0;
  if ((s > NP) || (s < NP)) {
    errorFn(1);
  } else {
    if ((compRegistered > 0) || (compRegistered < 0)) {
      errorFn(1);
    } else {
      compRegistered = 1;
      routine = 0;
    }
  }
  irpSp___0 = Irp__Tail__Overlay__CurrentStackLocation - 1;
  irpSp__Context = event;
  irpSp__Control = 224;
  status = IofCallDriver(deviceExtension__TargetDeviceObject, Irp);
  CIL___Tmp15 = (int )status;
  if ((CIL___Tmp15 >= 259) && (CIL___Tmp15 <= 259)) {
    KeWaitForSingleObject(event, Executive, KernelMode, 0, 0);
    status = myStatus;
  }
  return (status);
}
}
int DiskPerfCreate(int DeviceObject , int Irp ) 
{ 

  {
  myStatus = 0;
  IofCompleteRequest(Irp, 0);
  return (0);
}
}
int DiskPerfIoCompletion(int DeviceObject , int Irp , int Context ) 
{ int irpStack__MajorFunction ;
  int partitionCounters__BytesRead__QuadPart ;
  int Irp__IoStatus__Information ;
  int partitionCounters__ReadCount ;
  int partitionCounters__ReadTime__QuadPart ;
  int difference__QuadPart ;
  int partitionCounters__BytesWritten__QuadPart ;
  int partitionCounters__WriteCount ;
  int partitionCounters__WriteTime__QuadPart ;
  int Irp__Flags ;
  int partitionCounters__SplitCount ;
  int Irp__PendingReturned ;
  int partitionCounters ;
  int queueLen ;

  {
      CREST_int(queueLen);
      CREST_int(partitionCounters);
      CREST_int(Irp__PendingReturned);
      CREST_int(partitionCounters__SplitCount);
      CREST_int(Irp__Flags);
      CREST_int(partitionCounters__WriteTime__QuadPart);
      CREST_int(partitionCounters__WriteCount);
      CREST_int(partitionCounters__BytesWritten__QuadPart);
      CREST_int(difference__QuadPart);
      CREST_int(partitionCounters__ReadTime__QuadPart);
      CREST_int(partitionCounters__ReadCount);
      CREST_int(Irp__IoStatus__Information);
      CREST_int(partitionCounters__BytesRead__QuadPart);
      CREST_int(irpStack__MajorFunction);
  if ((partitionCounters >= 0) && (partitionCounters <= 0)) {
    return (0);
  }
  if (queueLen < 0) {

  }
  if ((queueLen >= 0) && (queueLen <= 0)) {

  }
  if ((irpStack__MajorFunction >= 3) && (irpStack__MajorFunction <= 3)) {
    partitionCounters__BytesRead__QuadPart = partitionCounters__BytesRead__QuadPart + Irp__IoStatus__Information;
    partitionCounters__ReadCount = partitionCounters__ReadCount + 1;
    partitionCounters__ReadTime__QuadPart = partitionCounters__ReadTime__QuadPart + difference__QuadPart;
  } else {
    partitionCounters__BytesWritten__QuadPart = partitionCounters__BytesWritten__QuadPart + Irp__IoStatus__Information;
    partitionCounters__WriteCount = partitionCounters__WriteCount + 1;
    partitionCounters__WriteTime__QuadPart = partitionCounters__WriteTime__QuadPart + difference__QuadPart;
  }
  if ((Irp__Flags > 8) || (Irp__Flags < 8)) {
    partitionCounters__SplitCount = partitionCounters__SplitCount + 1;
  }
  if (Irp__PendingReturned > 0 || Irp__PendingReturned < 0) {
    if ((pended >= 0) && (pended <= 0)) {
      pended = 1;
    } else {
      errorFn(1);
    }
  }
  return (0);
}
}
int DiskPerfDeviceControl(int DeviceObject , int Irp ) 
{ int Irp__CurrentLocation ;
  int Irp__Tail__Overlay__CurrentStackLocation ;
  int DeviceObject__DeviceExtension ;
  int deviceExtension__TargetDeviceObject ;
  int currentIrpStack__Parameters__DeviceIoControl__IoControlCode ;
  int currentIrpStack__Parameters__DeviceIoControl__OutputBufferLength ;
  int sizeof__DISK_PERFORMANCE ;
  int Irp__IoStatus__Information ;
  int deviceExtension__DiskCounters ;
  int Irp__AssociatedIrp__SystemBuffer ;
  int deviceExtension__Processors ;
  int totalCounters__QueueDepth ;
  int deviceExtension__QueueDepth ;
  int Irp__IoStatus__Status ;
  int deviceExtension ;
  int currentIrpStack ;
  int status ;
  int i ;
  int totalCounters ;
  int diskCounters ;
  int tmp ;
  int CIL___Tmp24 ;
  int CIL___Tmp25 ;
  int CIL___Tmp26 ;

  {
      CREST_int(CIL___Tmp26);
      CREST_int(CIL___Tmp25);
      CREST_int(CIL___Tmp24);
      CREST_int(tmp);
      CREST_int(diskCounters);
      CREST_int(totalCounters);
      CREST_int(i);
      CREST_int(status);
      CREST_int(currentIrpStack);
      CREST_int(deviceExtension);
      CREST_int(Irp__IoStatus__Status);
      CREST_int(deviceExtension__QueueDepth);
      CREST_int(totalCounters__QueueDepth);
      CREST_int(deviceExtension__Processors);
      CREST_int(Irp__AssociatedIrp__SystemBuffer);
      CREST_int(deviceExtension__DiskCounters);
      CREST_int(Irp__IoStatus__Information);
      CREST_int(sizeof__DISK_PERFORMANCE);
      CREST_int(currentIrpStack__Parameters__DeviceIoControl__OutputBufferLength);
      CREST_int(currentIrpStack__Parameters__DeviceIoControl__IoControlCode);
      CREST_int(deviceExtension__TargetDeviceObject);
      CREST_int(DeviceObject__DeviceExtension);
      CREST_int(Irp__Tail__Overlay__CurrentStackLocation);
      CREST_int(Irp__CurrentLocation);
  deviceExtension = DeviceObject__DeviceExtension;
  currentIrpStack = Irp__Tail__Overlay__CurrentStackLocation;
  CIL___Tmp24 = 32;
  CIL___Tmp25 = 458752;
  CIL___Tmp26 = 458784;
  if ((currentIrpStack__Parameters__DeviceIoControl__IoControlCode >= CIL___Tmp26) && (currentIrpStack__Parameters__DeviceIoControl__IoControlCode <= CIL___Tmp26)) {
    if (currentIrpStack__Parameters__DeviceIoControl__OutputBufferLength < sizeof__DISK_PERFORMANCE) {
      status = -1073741789;
      Irp__IoStatus__Information = 0;
    } else {
      diskCounters = deviceExtension__DiskCounters;
      if ((diskCounters >= 0) && (diskCounters <= 0)) {
        Irp__IoStatus__Status = -1073741823;
        myStatus = -1073741823;
        IofCompleteRequest(Irp, 0);
        return (-1073741823);
      }
      totalCounters = Irp__AssociatedIrp__SystemBuffer;
      totalCounters__QueueDepth = deviceExtension__QueueDepth;
      status = 0;
      Irp__IoStatus__Information = sizeof__DISK_PERFORMANCE;
    }
    Irp__IoStatus__Status = status;
    myStatus = status;
    IofCompleteRequest(Irp, 0);
    return (status);
  } else {
    Irp__CurrentLocation = Irp__CurrentLocation + 1;
    Irp__Tail__Overlay__CurrentStackLocation = Irp__Tail__Overlay__CurrentStackLocation + 1;
    tmp = IofCallDriver(deviceExtension__TargetDeviceObject, Irp);
    return (tmp);
  }
}
}
int DiskPerfShutdownFlush(int DeviceObject , int Irp ) 
{ int DeviceObject__DeviceExtension ;
  int Irp__CurrentLocation ;
  int Irp__Tail__Overlay__CurrentStackLocation ;
  int deviceExtension__TargetDeviceObject ;
  int deviceExtension ;
  int tmp ;

  {
      CREST_int(tmp);
      CREST_int(deviceExtension);
      CREST_int(deviceExtension__TargetDeviceObject);
      CREST_int(Irp__Tail__Overlay__CurrentStackLocation);
      CREST_int(Irp__CurrentLocation);
      CREST_int(DeviceObject__DeviceExtension);
  deviceExtension = DeviceObject__DeviceExtension;
  Irp__CurrentLocation = Irp__CurrentLocation + 1;
  Irp__Tail__Overlay__CurrentStackLocation = Irp__Tail__Overlay__CurrentStackLocation + 1;
  tmp = IofCallDriver(deviceExtension__TargetDeviceObject, Irp);
  return (tmp);
}
}
void DiskPerfUnload(int DriverObject ) 
{ 

  {
  return;
}
}
int IoBuildDeviceIoControlRequest(int IoControlCode , int DeviceObject , int InputBuffer , int InputBufferLength , int OutputBuffer , int OutputBufferLength , int InternalDeviceIoControl , int Event , int IoStatusBlock ) ;
int DiskPerfRegisterDevice(int DeviceObject ) 
{ int DeviceObject__DeviceExtension ;
  int deviceExtension__TargetDeviceObject ;
  int sizeof__number ;
  int ioStatus__Status ;
  int sizeof__VOLUME_NUMBER ;
  int volumeNumber__VolumeManagerName__0 ;
  int status ;
  int ioStatus ;
  int event ;
  int deviceExtension ;
  int irp ;
  int number ;
  int registrationFlag ;
  int sizeof__MOUNTDEV_NAME ;
  int output__NameLength ;
  int outputSize ;
  int output ;
  int volumeNumber ;
  int CIL___Tmp20 ;
  int CIL___Tmp21 ;
  int CIL___Tmp22 ;
  int CIL___Tmp23 ;
  int CIL___Tmp24 ;
  int CIL___Tmp25 ;
  int CIL___Tmp26 ;
  int CIL___Tmp27 ;
  int CIL___Tmp28 ;
  int CIL___Tmp29 ;
  int CIL___Tmp30 ;
  int CIL___Tmp31 ;
  int CIL___Tmp32 ;
  int CIL___Tmp34 ;
  int CIL___Tmp35 ;
  int CIL___Tmp36 ;
  int CIL___Tmp37 ;

  {
      CREST_int(CIL___Tmp37);
      CREST_int(CIL___Tmp36);
      CREST_int(CIL___Tmp35);
      CREST_int(CIL___Tmp34);
      CREST_int(CIL___Tmp32);
      CREST_int(CIL___Tmp31);
      CREST_int(CIL___Tmp30);
      CREST_int(CIL___Tmp29);
      CREST_int(CIL___Tmp28);
      CREST_int(CIL___Tmp27);
      CREST_int(CIL___Tmp26);
      CREST_int(CIL___Tmp25);
      CREST_int(CIL___Tmp24);
      CREST_int(CIL___Tmp23);
      CREST_int(CIL___Tmp22);
      CREST_int(CIL___Tmp21);
      CREST_int(CIL___Tmp20);
      CREST_int(volumeNumber);
      CREST_int(output);
      CREST_int(outputSize);
      CREST_int(output__NameLength);
      CREST_int(sizeof__MOUNTDEV_NAME);
      CREST_int(registrationFlag);
      CREST_int(number);
      CREST_int(irp);
      CREST_int(deviceExtension);
      CREST_int(event);
      CREST_int(ioStatus);
      CREST_int(status);
      CREST_int(volumeNumber__VolumeManagerName__0);
      CREST_int(sizeof__VOLUME_NUMBER);
      CREST_int(ioStatus__Status);
      CREST_int(sizeof__number);
      CREST_int(deviceExtension__TargetDeviceObject);
      CREST_int(DeviceObject__DeviceExtension);
  registrationFlag = 0;
  deviceExtension = DeviceObject__DeviceExtension;
  CIL___Tmp20 = 4224;
  CIL___Tmp21 = 2949120;
  CIL___Tmp22 = 2953344;
  irp = IoBuildDeviceIoControlRequest(CIL___Tmp22, deviceExtension__TargetDeviceObject, 0, 0, number, sizeof__number, 0, event, ioStatus);
  if (irp >= 0 && irp <= 0) {
    return (-1073741670);
  }
  status = IofCallDriver(deviceExtension__TargetDeviceObject, irp);
  CIL___Tmp23 = (int )status;
  if ((CIL___Tmp23 >= 259) && (CIL___Tmp23 <= 259)) {
    KeWaitForSingleObject(event, Executive, KernelMode, 0, 0);
    status = ioStatus__Status;
  }
  if (status < 0) {
    outputSize = sizeof__MOUNTDEV_NAME;
    if (output >= 0 && output <= 0) {
      return (-1073741670);
    }
    CIL___Tmp24 = 8;
    CIL___Tmp25 = 5046272;
    CIL___Tmp26 = 5046280;
    irp = IoBuildDeviceIoControlRequest(CIL___Tmp26, deviceExtension__TargetDeviceObject, 0, 0, output, outputSize, 0, event, ioStatus);
    if (irp >= 0 && irp <= 0) {
      return (-1073741670);
    }
    status = IofCallDriver(deviceExtension__TargetDeviceObject, irp);
    CIL___Tmp27 = (int )status;
    if ((CIL___Tmp27 >= 259) && (CIL___Tmp27 <= 259)) {
      KeWaitForSingleObject(event, Executive, KernelMode, 0, 0);
      status = ioStatus__Status;
    }
    CIL___Tmp28 = (int )status;
    if ((CIL___Tmp28 >= -2147483643) && (CIL___Tmp28 <= -2147483643)) {
      outputSize = sizeof__MOUNTDEV_NAME + output__NameLength;
      if (output >= 0 && output <= 0) {
        return (-1073741670);
      }
      CIL___Tmp29 = 8;
      CIL___Tmp30 = 5046272;
      CIL___Tmp31 = 5046280;
      irp = IoBuildDeviceIoControlRequest(CIL___Tmp31, deviceExtension__TargetDeviceObject, 0, 0, output, outputSize, 0, event, ioStatus);
      if (irp >= 0 && irp <= 0) {
        return (-1073741670);
      }
      status = IofCallDriver(deviceExtension__TargetDeviceObject, irp);
      CIL___Tmp32 = (int )status;
      if ((CIL___Tmp32 >= 259) && (CIL___Tmp32 <= 259)) {
        KeWaitForSingleObject(event, Executive, KernelMode, 0, 0);
        status = ioStatus__Status;
      }
    }
    if (status < 0) {
      return (status);
    }
    CIL___Tmp34 = 28;
    CIL___Tmp35 = 5636096;
    CIL___Tmp36 = 5636124;
    irp = IoBuildDeviceIoControlRequest(CIL___Tmp36, deviceExtension__TargetDeviceObject, 0, 0, volumeNumber, sizeof__VOLUME_NUMBER, 0, event, ioStatus);
    if (irp >= 0 && irp <= 0) {
      return (-1073741670);
    }
    status = IofCallDriver(deviceExtension__TargetDeviceObject, irp);
    CIL___Tmp37 = (int )status;
    if ((CIL___Tmp37 >= 259) && (CIL___Tmp37 <= 259)) {
      KeWaitForSingleObject(event, Executive, KernelMode, 0, 0);
      status = ioStatus__Status;
    }
    if (status < 0) {
      goto my_L;
    } else {
      if ((volumeNumber__VolumeManagerName__0 >= 0) && (volumeNumber__VolumeManagerName__0 <= 0)) {
        my_L: 
        if (status >= 0) {

        }
      }
    }
  }
  if (status < 0) {

  }
  return (status);
}
}
void stub_driver_init(void) 
{ 

  {
  s = NP;
  customIrp = 0;
  setEventCalled = customIrp;
  lowerDriverReturn = setEventCalled;
  compRegistered = lowerDriverReturn;
  compFptr = compRegistered;
  pended = compFptr;
  return;
}
}
int main(void) 
{ int d ;
  int status ;
  int we_should_unload ;
  int irp ;
  int pirp__IoStatus__Status ;
  int irp_choice ;
  int devobj ;
  int tmp_ndt_1 ;
  int tmp_ndt_2 ;
  int tmp_ndt_3 ;
  int tmp_ndt_4 ;
  int tmp_ndt_5 ;

  {
      CREST_int(tmp_ndt_5);
      CREST_int(tmp_ndt_4);
      CREST_int(tmp_ndt_3);
      CREST_int(tmp_ndt_2);
      CREST_int(tmp_ndt_1);
      CREST_int(devobj);
      CREST_int(irp_choice);
      CREST_int(pirp__IoStatus__Status);
      CREST_int(irp);
      CREST_int(we_should_unload);
      CREST_int(status);
      CREST_int(d);
  s = 0;
  UNLOADED = 0;
  NP = 0;
  DC = 0;
  SKIP1 = 0;
  SKIP2 = 0;
  MPR1 = 0;
  MPR3 = 0;
  IPC = 0;
  pended = 0;
  compFptr = 0;
  compRegistered = 0;
  lowerDriverReturn = 0;
  setEventCalled = 0;
  customIrp = 0;
  myStatus = 0;
  routine = 0;
  pirp = 0;
  Executive = 0;
  KernelMode = 0;
  pirp = irp;
  _BLAST_init();
  if (status >= 0) {
    s = NP;
    customIrp = 0;
    setEventCalled = customIrp;
    lowerDriverReturn = setEventCalled;
    compRegistered = lowerDriverReturn;
    compFptr = compRegistered;
    pended = compFptr;
    pirp__IoStatus__Status = 0;
    myStatus = 0;
    if ((irp_choice >= 0) && (irp_choice <= 0)) {
      pirp__IoStatus__Status = -1073741637;
      myStatus = -1073741637;
    }
    stub_driver_init();
    if (status < 0) {
      return (-1);
    }
    if ((tmp_ndt_1 >= 0) && (tmp_ndt_1 <= 0)) {
      goto myswitch_2_0;
    } else {
      if ((tmp_ndt_2 >= 2) && (tmp_ndt_2 <= 2)) {
        goto myswitch_2_2;
      } else {
        if ((tmp_ndt_3 >= 3) && (tmp_ndt_3 <= 3)) {
          goto myswitch_2_3;
        } else {
          if ((tmp_ndt_4 >= 4) && (tmp_ndt_4 <= 4)) {
            goto myswitch_2_4;
          } else {
            if ((tmp_ndt_5 >= 12) && (tmp_ndt_5 <= 12)) {
              goto myswitch_2_12;
            } else {
              goto myswitch_2_default;
              if (0) {
                myswitch_2_0: 
                status = DiskPerfCreate(devobj, pirp);
                goto myswitch_2_break;
                myswitch_2_2: 
                status = DiskPerfDeviceControl(devobj, pirp);
                goto myswitch_2_break;
                myswitch_2_3: 
                status = DiskPerfDispatchPnp(devobj, pirp);
                goto myswitch_2_break;
                myswitch_2_4: 
                status = DiskPerfDispatchPower(devobj, pirp);
                goto myswitch_2_break;
                myswitch_2_12: 
                status = DiskPerfShutdownFlush(devobj, pirp);
                goto myswitch_2_break;
                myswitch_2_default: ;
                return (-1);
              } else {
                myswitch_2_break: ;
              }
            }
          }
        }
      }
    }
    if (we_should_unload > 0 || we_should_unload < 0) {
      DiskPerfUnload(d);
    }
  }
  if ((pended >= 1) && (pended <= 1)) {
    if ((s >= NP) && (s <= NP)) {
      s = NP;
    } else {
      goto my_L___2;
    }
  } else {
    my_L___2: 
    if ((pended >= 1) && (pended <= 1)) {
      if ((s >= MPR3) && (s <= MPR3)) {
        s = MPR3;
      } else {
        goto my_L___1;
      }
    } else {
      my_L___1: 
      if ((s > UNLOADED) || (s < UNLOADED)) {
        if ((status > -1) || (status < -1)) {
          if ((s > SKIP2) || (s < SKIP2)) {
            if ((s > IPC) || (s < IPC)) {
              if ((s > DC) || (s < DC)) {
                errorFn(1);
              } else {
                goto my_L___0;
              }
            } else {
              goto my_L___0;
            }
          } else {
            my_L___0: 
            if ((pended >= 1) && (pended <= 1)) {
              if ((status > 259) || (status < 259)) {
                errorFn(1);
              }
            } else {
              if ((s >= DC) && (s <= DC)) {
                if ((status >= 259) && (status <= 259)) {
                  errorFn(1);
                }
              } else {
                if ((status > lowerDriverReturn) || (status < lowerDriverReturn)) {
                  errorFn(1);
                }
              }
            }
          }
        }
      }
    }
  }
  return (status);
}
}
int IoBuildDeviceIoControlRequest(int IoControlCode , int DeviceObject , int InputBuffer , int InputBufferLength , int OutputBuffer , int OutputBufferLength , int InternalDeviceIoControl , int Event , int IoStatusBlock ) 
{ int malloc_ret ;
  int tmp_ndt_7 ;

  {
      CREST_int(tmp_ndt_7);
      CREST_int(malloc_ret);
  customIrp = 1;
  if ((tmp_ndt_7 >= 0) && (tmp_ndt_7 <= 0)) {
    goto myswitch_3_0;
  } else {
    goto myswitch_3_default;
    if (0) {
      myswitch_3_0: ;
      return (malloc_ret);
      myswitch_3_default: ;
      return (0);
    }
  }
}
}
void stubMoreProcessingRequired(void) 
{ 

  {
  if ((s >= NP) && (s <= NP)) {
    s = MPR1;
  } else {
    errorFn(1);
  }
  return;
}
}
int IofCallDriver(int DeviceObject , int Irp ) 
{ int returnVal2 ;
  int compRetStatus ;
  int lcontext ;
  int CIL___Tmp7 ;
  int tmp_ndt_8 ;
  int tmp_ndt_9 ;

  {
      CREST_int(tmp_ndt_9);
      CREST_int(tmp_ndt_8);
      CREST_int(CIL___Tmp7);
      CREST_int(lcontext);
      CREST_int(compRetStatus);
      CREST_int(returnVal2);
  if (compRegistered > 0 || compRegistered < 0) {
    if ((routine >= 0) && (routine <= 0)) {
      compRetStatus = DiskPerfIrpCompletion(DeviceObject, Irp, lcontext);
    } else {
      compRetStatus = DiskPerfIoCompletion(DeviceObject, Irp, lcontext);
    }
    CIL___Tmp7 = (int )compRetStatus;
    if ((CIL___Tmp7 >= -1073741802) && (CIL___Tmp7 <= -1073741802)) {
      stubMoreProcessingRequired();
    }
  }
  if ((tmp_ndt_8 >= 0) && (tmp_ndt_8 <= 0)) {
    goto myswitch_4_0;
  } else {
    if ((tmp_ndt_9 >= 1) && (tmp_ndt_9 <= 1)) {
      goto myswitch_4_1;
    } else {
      goto myswitch_4_default;
      if (0) {
        myswitch_4_0: 
        returnVal2 = 0;
        goto myswitch_4_break;
        myswitch_4_1: 
        returnVal2 = -1073741823;
        goto myswitch_4_break;
        myswitch_4_default: 
        returnVal2 = 259;
        goto myswitch_4_break;
      } else {
        myswitch_4_break: ;
      }
    }
  }
  if ((s >= NP) && (s <= NP)) {
    s = IPC;
    lowerDriverReturn = returnVal2;
  } else {
    if ((s >= MPR1) && (s <= MPR1)) {
      if ((returnVal2 >= 259) && (returnVal2 <= 259)) {
        s = MPR3;
        lowerDriverReturn = returnVal2;
      } else {
        s = NP;
        lowerDriverReturn = returnVal2;
      }
    } else {
      if ((s >= SKIP1) && (s <= SKIP1)) {
        s = SKIP2;
        lowerDriverReturn = returnVal2;
      } else {
        errorFn(1);
      }
    }
  }
  return (returnVal2);
}
}
void IofCompleteRequest(int Irp , int PriorityBoost ) 
{ 

  {
  if ((s >= NP) && (s <= NP)) {
    s = DC;
  } else {
    errorFn(1);
  }
  return;
}
}
int KeSetEvent(int Event , int Increment , int Wait ) 
{ int l ;

  {
      CREST_int(l);
  setEventCalled = 1;
  return (l);
}
}
int KeWaitForSingleObject(int Object , int WaitReason , int WaitMode , int Alertable , int Timeout ) 
{ int tmp_ndt_10 ;

  {
      CREST_int(tmp_ndt_10);
  if ((s >= MPR3) && (s <= MPR3)) {
    if ((setEventCalled >= 1) && (setEventCalled <= 1)) {
      s = NP;
      setEventCalled = 0;
    } else {
      goto my_L;
    }
  } else {
    my_L: 
    if ((customIrp >= 1) && (customIrp <= 1)) {
      s = NP;
      customIrp = 0;
    } else {
      if ((s >= MPR3) && (s <= MPR3)) {
        errorFn(1);
      }
    }
  }
  if ((tmp_ndt_10 >= 0) && (tmp_ndt_10 <= 0)) {
    goto myswitch_5_0;
  } else {
    goto myswitch_5_default;
    if (0) {
      myswitch_5_0: ;
      return (0);
      myswitch_5_default: ;
      return (-1073741823);
    }
  }
}
}
int PoCallDriver(int DeviceObject , int Irp ) 
{ int compRetStatus ;
  int returnVal ;
  int lcontext ;
  int CIL___Tmp7 ;
  int CIL___Tmp8 ;
  int tmp_ndt_11 ;
  int tmp_ndt_12 ;

  {
      CREST_int(tmp_ndt_12);
      CREST_int(tmp_ndt_11);
      CREST_int(CIL___Tmp8);
      CREST_int(CIL___Tmp7);
      CREST_int(lcontext);
      CREST_int(returnVal);
      CREST_int(compRetStatus);
  if (compRegistered > 0 || compRegistered < 0) {
    if ((routine >= 0) && (routine <= 0)) {
      compRetStatus = DiskPerfIrpCompletion(DeviceObject, Irp, lcontext);
    } else {
      if ((routine >= 1) && (routine <= 1)) {
        compRetStatus = DiskPerfIoCompletion(DeviceObject, Irp, lcontext);
      }
    }
    CIL___Tmp7 = (int )compRetStatus;
    if ((CIL___Tmp7 >= -1073741802) && (CIL___Tmp7 <= -1073741802)) {
      stubMoreProcessingRequired();
    }
  }
  if ((tmp_ndt_11 >= 0) && (tmp_ndt_11 <= 0)) {
    goto myswitch_6_0;
  } else {
    if ((tmp_ndt_12 >= 1) && (tmp_ndt_12 <= 1)) {
      goto myswitch_6_1;
    } else {
      goto myswitch_6_default;
      if (0) {
        myswitch_6_0: 
        returnVal = 0;
        goto myswitch_6_break;
        myswitch_6_1: 
        returnVal = -1073741823;
        goto myswitch_6_break;
        myswitch_6_default: 
        returnVal = 259;
        goto myswitch_6_break;
      } else {
        myswitch_6_break: ;
      }
    }
  }
  if ((s >= NP) && (s <= NP)) {
    s = IPC;
    lowerDriverReturn = returnVal;
  } else {
    if ((s >= MPR1) && (s <= MPR1)) {
      CIL___Tmp8 = (int )returnVal;
      if ((CIL___Tmp8 >= 259) && (CIL___Tmp8 <= 259)) {
        s = MPR3;
        lowerDriverReturn = returnVal;
      } else {
        s = NP;
        lowerDriverReturn = returnVal;
      }
    } else {
      if ((s >= SKIP1) && (s <= SKIP1)) {
        s = SKIP2;
        lowerDriverReturn = returnVal;
      } else {
        errorFn(1);
      }
    }
  }
  return (returnVal);
}
}
